-- This is generally a bad practice

DROP TABLE IF EXISTS SOURCE_TABLE;
CREATE TABLE SOURCE_TABLE AS SELECT * FROM sources.amis_source_table;

ALTER TABLE SOURCE_TABLE ADD 
	COLUMN DOMAIN_ID VARCHAR(20),
	ADD COLUMN ATC_CODE VARCHAR(1023),
	ADD COLUMN BRAND_NAME VARCHAR(1023);
