
DROP TABLE IF EXISTS ST_1;
DROP TABLE IF EXISTS ST_2;
DROP TABLE IF EXISTS ST_3;
DROP TABLE IF EXISTS ST_3_box;
DROP TABLE IF EXISTS ST_4;
DROP TABLE IF EXISTS ST_5;

DROP TABLE IF EXISTS STRENGTH_TMP;
DROP TABLE IF EXISTS DENORM_LIST;

DROP TABLE IF EXISTS DRUGS_AND_PACKS;
DROP TABLE IF EXISTS SOURCE_TABLE_PACK;


DROP TABLE IF EXISTS forms;
DROP TABLE IF EXISTS Brand_name;
DROP TABLE IF EXISTS unit;
DROP TABLE IF EXISTS manuf;

DROP TABLE IF EXISTS dcs_form;
DROP TABLE IF EXISTS dcs_bn;
DROP TABLE IF EXISTS dcs_drug;
DROP TABLE IF EXISTS dcs_ingr;
DROP TABLE IF EXISTS dcs_unit;
DROP TABLE IF EXISTS dcs_manuf;



DROP TABLE IF EXISTS STP_1;
DROP TABLE IF EXISTS STP_2;
DROP TABLE IF EXISTS STP_3;
DROP TABLE IF EXISTS STP_TP1;

