-- UPDATE SOURCE_TABLE SET ATC_CODE = regexp_replace(regexp_replace(IND, '\s.*','','g'), '^"','','g');

UPDATE SOURCE_TABLE
SET ATC_CODE = regexp_replace(IND, '\s.*', '', 'g');

UPDATE SOURCE_TABLE
SET DOMAIN_ID = 'Device'
WHERE IND LIKE 'B05AX03%'
	OR IND LIKE 'B05AX02%'
	OR IND LIKE 'B05AX01%'
	OR IND LIKE 'V09%'
	OR IND LIKE 'V08%'
	OR IND LIKE 'V04%'
	OR IND LIKE 'B05AX04%'
	OR IND LIKE 'B05ZB%'
	OR IND LIKE '%B05AX %'
	OR IND LIKE '%D03AX32%'
	OR IND LIKE '%V03AX%'
	OR IND LIKE 'V10%'
	OR IND LIKE 'V %'
	OR ind LIKE '%V03AN%';

UPDATE SOURCE_TABLE
SET DOMAIN_ID = 'Drug'
WHERE DOMAIN_ID IS NULL;

