DROP TABLE IF EXISTS st_1;
CREATE TABLE st_1 AS
SELECT a.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_1 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_1 IS NOT NULL

UNION

SELECT a.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_2 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_2 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_3 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_3 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_4 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_4 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_5 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_5 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_6 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_6 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_7 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_7 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_8 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_8 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_9 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_9 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_10 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_10 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_11 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_11 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_12 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_12 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_13 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_13 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_14 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_14 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_15 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_15 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_16 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_16 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_17 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_17 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_18 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_18 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_19 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_19 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_20 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_20 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_21 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_21 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_22 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_22 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_23 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_23 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_24 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_24 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_25 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_25 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_26 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_26 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_27 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_27 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_28 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_28 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_29 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_29 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_30 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_30 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_31 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_31 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_32 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_32 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_33 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_33 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_34 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_34 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_35 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_35 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_36 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_36 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_37 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_37 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_38 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_38 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_39 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_39 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_40 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_40 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_41 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_41 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_42 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_42 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_43 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_43 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_44 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_44 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_45 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_45 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_46 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_46 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_47 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_47 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_48 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_48 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_49 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_49 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_50 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_50 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_51 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_51 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_52 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_52 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_53 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_53 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_54 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_54 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_55 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_55 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_56 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_56 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_57 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_57 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_58 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_58 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_59 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_59 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_60 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_60 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_61 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_61 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_62 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_62 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_63 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_63 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_64 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_64 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_65 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_65 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_66 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_66 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_67 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_67 IS NOT NULL

UNION

SELECT A.DRUG_CODE,
	INGREDIENT_CODE,
	AMOUNT_VALUE,
	AMOUNT_UNIT,
	NUMERATOR_VALUE,
	NUMERATOR_UNIT,
	DENOMINATOR_VALUE,
	DENOMINATOR_UNIT,
	AM,
	BM1,
	TPACK_68 AS TPACK
FROM STRENGTH_TMP a
JOIN DRUGS_AND_PACKS b ON a.drug_code = b.drug_code
WHERE TPACK_68 IS NOT NULL;

--extracting real denominator_value+
DROP TABLE IF EXISTS st_2;
CREATE TABLE st_2 AS
SELECT DISTINCT denom_value::FLOAT,
	denom_unit,
	drug_code,
	ingredient_code,
	amount_value,
	amount_unit,
	numerator_unit,
	numerator_value,
	tpack,
	denominator_unit,
	denominator_value,
	CONCAT (
		denom_value::FLOAT,
		denom_unit,
		' ',
		AM
		) AS drug_name
FROM (
	SELECT *
	FROM (
		SELECT substring(tpack, '([[:digit:]\.]+)(ml|g|cm|mg)+') AS denom_value,
			substring(tpack, '[[:digit:]\.]+(ml|g|cm|mg)+') AS denom_unit,
			drug_code,
			ingredient_code,
			amount_value,
			amount_unit,
			numerator_unit,
			numerator_value,
			tpack,
			denominator_unit,
			denominator_value,
			am
		FROM st_1
		WHERE substring(tpack, '([[:digit:]\.]+)(ml|g|cm|mg)+') IS NOT NULL
			AND denominator_value IS NOT NULL
			AND numerator_value IS NOT NULL
		) AS s0
	WHERE length(denom_value) - length(replace(denom_value, '.', '')) = 1 --count of '.'
	) AS s1;

--updating numerator_value as we changed denominator_value with tpack data
DROP TABLE IF EXISTS st_3;
CREATE TABLE st_3 AS
SELECT CASE 
		--when drug_code in (select enr from SOURCE_TABLE_PACK)  then numerator_value 
		WHEN denominator_unit = 'l'
			AND denom_unit = 'ml'
			THEN (denom_value * numerator_value / denominator_value) / 1000
		ELSE denom_value / denominator_value * numerator_value
		END AS numerator_value,
	denom_value AS denominator_value,
	denom_unit AS denominator_unit,
	drug_code,
	ingredient_code,
	amount_value,
	amount_unit,
	numerator_unit,
	tpack,
	drug_name,
	NULL::INT4 AS box_size
FROM st_2;

--extracting box_size
DROP TABLE IF EXISTS st_3_box;
CREATE TABLE st_3_box AS
SELECT numerator_value,
	denominator_value,
	drug_code,
	ingredient_code,
	amount_value,
	amount_unit,
	numerator_unit,
	denominator_unit,
	tpack,
	CONCAT (
		drug_name,
		' [Box of ',
		substring(tpack, '\d+'),
		']'
		) AS drug_name,
	CASE 
		WHEN substring(tpack, '.*\d+x*') = tpack
			THEN substring(tpack, '\d+')
		WHEN tpack ~ '\d+x'
			THEN substring(tpack, '\d+')
		ELSE NULL
		END::int4 AS box_size
FROM st_3
WHERE substring(tpack, '.*\d+x*') = tpack
	OR tpack ~ '\d+x';

DROP TABLE IF EXISTS st_4;
CREATE TABLE st_4 AS
SELECT drug_code,
	ingredient_code,
	amount_value,
	amount_unit,
	numerator_value,
	numerator_unit,
	denominator_value,
	denominator_unit,
	box_size,
	drug_name
FROM st_3

UNION

SELECT drug_code,
	ingredient_code,
	amount_value,
	amount_unit,
	numerator_value,
	numerator_unit,
	denominator_value,
	denominator_unit,
	box_size,
	drug_name
FROM st_3_box;

DROP TABLE IF EXISTS st_5;
CREATE TABLE st_5 AS
SELECT drug_code,
	ingredient_code,
	amount_value,
	amount_unit,
	numerator_value,
	numerator_unit,
	denominator_value,
	denominator_unit,
	box_size,
	drug_name,
	'OMOP' || nextval('new_voc') AS new_code
FROM st_4;

--inserting quant_drugs and boxes
ALTER TABLE strength_tmp ADD box_size int4;
INSERT INTO strength_tmp (
	drug_code,
	ingredient_code,
	amount_value,
	amount_unit,
	numerator_value,
	numerator_unit,
	denominator_value,
	denominator_unit,
	box_size
	)
SELECT new_code,
	ingredient_code,
	amount_value,
	amount_unit,
	numerator_value,
	numerator_unit,
	denominator_value,
	denominator_unit,
	box_size
FROM st_5;