--Prerequisites
--google_pack must be installed

--create a new schema
CREATE SCHEMA cde_groups AUTHORIZATION devv5;
ALTER DEFAULT PRIVILEGES IN SCHEMA cde_groups GRANT SELECT ON TABLES TO role_read_only;
GRANT USAGE ON SCHEMA cde_groups TO role_read_only;

--create a manual table for groups (in your dev-schema)
DROP TABLE IF EXISTS cde_manual_group;
CREATE TABLE cde_manual_group (
	source_code TEXT NOT NULL,
	source_code_description TEXT,
	source_vocabulary_id TEXT NOT NULL,
	group_id INT4 GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME seq_cde_manual_group),
	group_name TEXT NOT NULL,
	target_concept_id INT4
);
CREATE UNIQUE INDEX idx_pk_cde_manual_group ON cde_manual_group ((source_code || ':' || source_vocabulary_id));
CREATE INDEX idx_cde_manual_group_gid ON cde_manual_group (group_id);

--run all *.sql files