OPTIONS (errors=0, direct=true)
LOAD DATA 
CHARACTERSET WE8ISO8859P1
INFILE 'CMS32_DESC_LONG_DX.txt'
BADFILE 'CMS_DESC_LONG_DX.bad'
DISCARDFILE 'CMS_DESC_LONG_DX.dsc'
TRUNCATE
INTO TABLE CMS_DESC_LONG_DX
(
	CODE position(1:6), 
	NAME position(7:263) 
)