-- This is generally a bad practice

ALTER TABLE SOURCE_TABLE
  ADD (DOMAIN_ID  VARCHAR2(20 Byte),
       ATC_CODE   VARCHAR2(1023 Byte));

ALTER TABLE SOURCE_TABLE
  ADD BRAND_NAME VARCHAR2(1023 Byte);
