
DROP TABLE ST_1 CASCADE CONSTRAINTS PURGE;
DROP TABLE ST_2 CASCADE CONSTRAINTS PURGE;
DROP TABLE ST_3 CASCADE CONSTRAINTS PURGE;
DROP TABLE ST_3_box CASCADE CONSTRAINTS PURGE;
DROP TABLE ST_4 CASCADE CONSTRAINTS PURGE;
DROP TABLE ST_5 CASCADE CONSTRAINTS PURGE;

DROP TABLE STRENGTH_TMP CASCADE CONSTRAINTS PURGE;
DROP TABLE DENORM_LIST CASCADE CONSTRAINTS PURGE;

DROP TABLE DRUGS_AND_PACKS CASCADE CONSTRAINTS PURGE;
DROP TABLE SOURCE_TABLE_PACK CASCADE CONSTRAINTS PURGE;


DROP TABLE forms CASCADE CONSTRAINTS PURGE;
DROP TABLE Brand_name CASCADE CONSTRAINTS PURGE;
DROP TABLE unit CASCADE CONSTRAINTS PURGE;
DROP TABLE manuf CASCADE CONSTRAINTS PURGE;

DROP TABLE dcs_form CASCADE CONSTRAINTS PURGE;
DROP TABLE dcs_bn CASCADE CONSTRAINTS PURGE;
DROP TABLE dcs_drug CASCADE CONSTRAINTS PURGE;
DROP TABLE dcs_ingr CASCADE CONSTRAINTS PURGE;
DROP TABLE dcs_unit CASCADE CONSTRAINTS PURGE;
DROP TABLE dcs_manuf CASCADE CONSTRAINTS PURGE;



DROP TABLE STP_1 CASCADE CONSTRAINTS PURGE;
DROP TABLE STP_2 CASCADE CONSTRAINTS PURGE;
DROP TABLE STP_3 CASCADE CONSTRAINTS PURGE;
DROP TABLE STP_TP1 CASCADE CONSTRAINTS PURGE;

