
create table st_1 as(
SELECT a.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_1	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code where	TPACK_1	is not NULL UNION
SELECT a.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_2	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code where	TPACK_2	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_3	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_3	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_4	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_4	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_5	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_5	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_6	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_6	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_7	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_7	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_8	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_8	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_9	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_9	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_10 as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_10	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_11	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_11	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_12	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_12	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_13	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_13	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_14	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_14	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_15	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_15	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_16	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_16	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_17	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_17	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_18	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_18	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_19	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_19	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_20	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_20	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_21	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_21	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_22	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_22	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_23	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_23	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_24	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_24	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_25	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_25	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_26	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_26	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_27	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_27	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_28	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_28	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_29	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_29	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_30	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_30	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_31	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_31	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_32	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_32	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_33	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_33	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_34	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_34	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_35	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_35	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_36	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_36	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_37	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_37	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_38	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_38	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_39	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_39	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_40	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_40	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_41	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_41	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_42	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_42	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_43	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_43	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_44	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_44	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_45	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_45	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_46	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_46	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_47	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_47	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_48	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_48	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_49	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_49	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_50	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_50	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_51	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_51	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_52	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_52	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_53	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_53	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_54	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_54	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_55	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_55	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_56	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_56	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_57	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_57	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_58	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_58	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_59	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_59	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_60	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_60	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_61	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_61	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_62	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_62	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_63	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_63	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_64	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_64	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_65	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_65	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_66	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_66	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_67	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_67	is not NULL UNION
SELECT A.DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT	,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE	,DENOMINATOR_UNIT,	AM,BM1,	TPACK_68	as TPACK	from STRENGTH_TMP a join DRUGS_AND_PACKS b on a.drug_code=b.drug_code  where	TPACK_68	is not NULL 
);
--extracting real denominator_value+
create table st_2 as(
 select distinct regexp_substr(trim(regexp_substr (tpack,'(\d+\.*\d*)+(ml|g|cm)+',1)), '[[:digit:]\.]+') as denom_value,
regexp_replace (trim(regexp_substr (tpack,'[[:digit:]\.]+(ml|g|cm)+',1)),'[[:digit:]\.]+') as denom_unit,
DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_UNIT, numerator_value,tpack,denominator_unit,denominator_value,
regexp_substr(trim(regexp_substr (tpack,'(\d+\.*\d*)+(ml|g|cm)+',1)), '[[:digit:]\.]+')||regexp_replace (trim(regexp_substr (tpack,'[[:digit:]\.]+(ml|g|cm)+',1)),'[[:digit:]\.]+')||' '||AM as drug_name
from st_1 where regexp_substr(trim(regexp_substr (tpack,'[[:digit:]\.]+(ml|g|cm)+',1)), '[[:digit:]\.]+') is not null and  denominator_value is not null and  numerator_value is not null 
)
;

UPDATE ST_2   SET DENOM_VALUE = '1.193' WHERE DENOM_VALUE = '0.1.193' AND   DRUG_CODE = '2188062' AND   INGREDIENT_CODE = '22408-8';
--updating numerator_value as we changed denominator_value with tpack data
create table st_3 as (
select
case
--when drug_code in (select enr from SOURCE_TABLE_PACK)  then numerator_value 
when denominator_unit='l' and denom_unit='ml'  
then  (denom_value*numerator_value/denominator_value)/1000 
else to_number(denom_value)/denominator_value*numerator_value
end as numerator_value,
denom_value as denominator_value,denom_unit as denominator_unit,DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_UNIT, tpack ,drug_name
from st_2)
;
alter table st_3 
add box_size varchar(255);
--extracting box_size
create table st_3_box as(
select NUMERATOR_VALUE,DENOMINATOR_VALUE,DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_UNIT,DENOMINATOR_UNIT,TPACK, 
drug_name||' [Box of '||regexp_substr(tpack, '\d+')||']' as drug_name,
case when regexp_substr (tpack, '.*\d+x*') = tpack 
then regexp_substr (tpack, '\d+') 
when regexp_like (tpack, '\d+x') then regexp_substr (tpack, '\d+') else null end as box_size 
from  st_3
where regexp_substr (tpack, '.*\d+x*') = tpack  or regexp_like (tpack, '\d+x') );

create table st_4 as 
( select distinct DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT,box_size,drug_name from st_3
 union select distinct DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT,box_size,drug_name from st_3_box);
 
create table st_5 as(select DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT,box_size,drug_name,'OMOP'||new_voc.nextval as new_code from st_4);

--inserting quant_drugs and boxes
alter table strength_tmp
add box_size number;
insert into strength_tmp (DRUG_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT,box_size)
select NEW_CODE,INGREDIENT_CODE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT,box_size from st_5;
