TRUNCATE TABLE cde_manual_group;
DROP TABLE IF EXISTS cde_manual_group;
CREATE TABLE cde_manual_group (
	source_code TEXT NOT NULL,
	source_code_description TEXT,
	source_vocabulary_id TEXT NOT NULL,
	group_id INT4 GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME seq_cde_manual_group),
	group_name TEXT NOT NULL
);

CREATE UNIQUE INDEX idx_pk_cde_manual_group ON cde_manual_group ((source_code || ':' || source_vocabulary_id));
CREATE INDEX idx_cde_manual_group_gid ON cde_manual_group (group_id);

--Server functions
--test Case 1:
SELECT cde_groups.SplitGroup('cde_manual_group',2);
--test Case 1a:
SELECT cde_groups.DetachConceptFromGroup('cde_manual_group',ARRAY['A18.002:ICD10CN']);
--test Case 2:
SELECT cde_groups.MergeGroupsByConcept('cde_manual_group', 3, ARRAY['H40.149:ICD10CM']);
--test Case 2a:
SELECT cde_groups.MergeGroupsByGroupID('cde_manual_group', 1, 2, 3);
--test Case 2b:
SELECT cde_groups.MergeSeparateConcepts('cde_manual_group', ARRAY['A18.002:ICD10CN','T80.902:ICD10CN']);

--Functions to proceed Google sheets
--test: mapping harmonization
SELECT cde_groups.GSheetMappingHarmonization('cde_manual_group', '1a3os1cjgIuji7Q4me9DAzt1wb49hew3X4OURLRuyACs','Test_set_groups');
--test Case 2.1: merge groups
SELECT cde_groups.GSheetMergeGroups('cde_manual_group', '1a3os1cjgIuji7Q4me9DAzt1wb49hew3X4OURLRuyACs','Test_set_groups');
--test The rest of the cases (split the group, regroup concepts within one group, detach concepts and add them into the group not represented in the spreadsheet
SELECT cde_groups.GSheetReGroup('cde_manual_group', '1a3os1cjgIuji7Q4me9DAzt1wb49hew3X4OURLRuyACs','Test_set_concepts'); ----Split the group case, regroup concepts within one group case 1/2, detach (то есть общая функция для всех остальных случаев)
--to add function output as a new tab in a spreadsheet
SELECT google_pack.SetSpreadSheet ('cde_manual_group', '1a3os1cjgIuji7Q4me9DAzt1wb49hew3X4OURLRuyACs', 'test automation')
