--ds_1 for drugs and ds_pack_1 for packs
insert into ds_stage (DRUG_CONCEPT_CODE,INGREDIENT_CONCEPT_CODE,BOX_SIZE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT)
select distinct cast (CONCEPT_CODE as varchar (200)) as CONCEPT_CODE,INGREDIENT_CODE,BOX_SIZE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT from ds_1 
WHERE concept_code not in (select concept_code from PACK_CONT_1)
union 
select distinct PACK_COMPONENT_CODE,INGREDIENT_CODE,BOX_SIZE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT from ds_pack_1
;
--sum up the same ingredients manualy
DELETE FROM DS_STAGE WHERE  DRUG_CONCEPT_CODE = '3087355' AND   INGREDIENT_CONCEPT_CODE = '5356' AND   BOX_SIZE = 20 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 1.4 AND   NUMERATOR_UNIT = 'g' AND   DENOMINATOR_VALUE = 10 AND   DENOMINATOR_UNIT = 'g';
DELETE FROM DS_STAGE WHERE  DRUG_CONCEPT_CODE = '3200509' AND   INGREDIENT_CONCEPT_CODE = '1261' AND   BOX_SIZE = 1 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 5 AND   NUMERATOR_UNIT = 'mg' AND   DENOMINATOR_VALUE = 1 AND   DENOMINATOR_UNIT = 'ml';
DELETE FROM DS_STAGE WHERE  DRUG_CONCEPT_CODE = '3205777' AND   INGREDIENT_CONCEPT_CODE = '1261' AND   BOX_SIZE = 1 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 3 AND   NUMERATOR_UNIT = 'mg' AND   DENOMINATOR_VALUE = 1 AND   DENOMINATOR_UNIT = 'ml';
DELETE FROM DS_STAGE WHERE  DRUG_CONCEPT_CODE = '3698389' AND   INGREDIENT_CONCEPT_CODE = '563' AND   BOX_SIZE = 10 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 0.695 AND   NUMERATOR_UNIT = 'g' AND   DENOMINATOR_VALUE = 500 AND   DENOMINATOR_UNIT = 'ml';
DELETE FROM DS_STAGE WHERE  DRUG_CONCEPT_CODE = '3698426' AND   INGREDIENT_CONCEPT_CODE = '563' AND   BOX_SIZE = 10 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 1.2 AND   NUMERATOR_UNIT = 'g' AND   DENOMINATOR_VALUE = 500 AND   DENOMINATOR_UNIT = 'ml';
DELETE FROM DS_STAGE WHERE  DRUG_CONCEPT_CODE = '5536774' AND   INGREDIENT_CONCEPT_CODE = '1261' AND   BOX_SIZE = 25 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 3 AND   NUMERATOR_UNIT = 'mg' AND   DENOMINATOR_VALUE = 1 AND   DENOMINATOR_UNIT = 'ml';
UPDATE DS_STAGE   SET NUMERATOR_VALUE = 2.5 WHERE  DRUG_CONCEPT_CODE = '3087355' AND   INGREDIENT_CONCEPT_CODE = '5356' AND   BOX_SIZE = 20 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 1.1 AND   NUMERATOR_UNIT = 'g' AND   DENOMINATOR_VALUE = 10 AND   DENOMINATOR_UNIT = 'g';
UPDATE DS_STAGE   SET NUMERATOR_VALUE = 7 WHERE  DRUG_CONCEPT_CODE = '3200509' AND   INGREDIENT_CONCEPT_CODE = '1261' AND   BOX_SIZE = 1 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 2 AND   NUMERATOR_UNIT = 'mg' AND   DENOMINATOR_VALUE = 1 AND   DENOMINATOR_UNIT = 'ml';
UPDATE DS_STAGE   SET NUMERATOR_VALUE = 5.7 WHERE  DRUG_CONCEPT_CODE = '3205777' AND   INGREDIENT_CONCEPT_CODE = '1261' AND   BOX_SIZE = 1 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 2.7 AND   NUMERATOR_UNIT = 'mg' AND   DENOMINATOR_VALUE = 1 AND   DENOMINATOR_UNIT = 'ml';
UPDATE DS_STAGE   SET NUMERATOR_VALUE = 1.715 WHERE  DRUG_CONCEPT_CODE = '3698389' AND   INGREDIENT_CONCEPT_CODE = '563' AND   BOX_SIZE = 10 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 1.015 AND   NUMERATOR_UNIT = 'g' AND   DENOMINATOR_VALUE = 500 AND   DENOMINATOR_UNIT = 'ml';
UPDATE DS_STAGE   SET NUMERATOR_VALUE = 2.795 WHERE  DRUG_CONCEPT_CODE = '3698426' AND   INGREDIENT_CONCEPT_CODE = '563' AND   BOX_SIZE = 10 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 1.595 AND   NUMERATOR_UNIT = 'g' AND   DENOMINATOR_VALUE = 500 AND   DENOMINATOR_UNIT = 'ml';
UPDATE DS_STAGE   SET NUMERATOR_VALUE = 5.7 WHERE  DRUG_CONCEPT_CODE = '5536774' AND   INGREDIENT_CONCEPT_CODE = '1261' AND   BOX_SIZE = 25 AND   AMOUNT_VALUE IS NULL AND   AMOUNT_UNIT IS NULL AND   NUMERATOR_VALUE = 2.7 AND   NUMERATOR_UNIT = 'mg' AND   DENOMINATOR_VALUE = 1 AND   DENOMINATOR_UNIT = 'ml';
;
DELETE FROM DS_STAGE WHERE DRUG_CONCEPT_CODE = '3284943' AND   INGREDIENT_CONCEPT_CODE = '29848' AND   BOX_SIZE = 5 AND   AMOUNT_VALUE = 0.23 AND   AMOUNT_UNIT = 'mg';
DELETE FROM DS_STAGE WHERE DRUG_CONCEPT_CODE = '3354164' AND   INGREDIENT_CONCEPT_CODE = '1023' AND   BOX_SIZE = 24 AND   AMOUNT_VALUE = 300 AND   AMOUNT_UNIT = 'mg';
DELETE FROM DS_STAGE WHERE DRUG_CONCEPT_CODE = '3404695'  AND   INGREDIENT_CONCEPT_CODE = '2202'  AND   BOX_SIZE = 24  AND   AMOUNT_VALUE = 62.5  AND   AMOUNT_UNIT = 'mg';
DELETE FROM DS_STAGE WHERE DRUG_CONCEPT_CODE = '5758486'  AND   INGREDIENT_CONCEPT_CODE = '29848'  AND   BOX_SIZE = 30  AND   AMOUNT_VALUE = 0.23  AND   AMOUNT_UNIT = 'mg';
DELETE FROM DS_STAGE WHERE DRUG_CONCEPT_CODE = '3584846'  AND   INGREDIENT_CONCEPT_CODE = '1023'  AND   BOX_SIZE = 30  AND   AMOUNT_VALUE = 500  AND   AMOUNT_UNIT = 'mg';
UPDATE DS_STAGE   SET AMOUNT_VALUE = 1.53 WHERE DRUG_CONCEPT_CODE = '3284943'  AND   INGREDIENT_CONCEPT_CODE = '29848'  AND   BOX_SIZE = 5  AND   AMOUNT_VALUE = 1.31  AND   AMOUNT_UNIT = 'mg';
UPDATE DS_STAGE   SET AMOUNT_VALUE = 500 WHERE DRUG_CONCEPT_CODE = '3354164'  AND   INGREDIENT_CONCEPT_CODE = '1023'  AND   BOX_SIZE = 24  AND   AMOUNT_VALUE = 200  AND   AMOUNT_UNIT = 'mg';
UPDATE DS_STAGE   SET AMOUNT_VALUE = 250 WHERE DRUG_CONCEPT_CODE = '3404695'  AND   INGREDIENT_CONCEPT_CODE = '2202'  AND   BOX_SIZE = 24  AND   AMOUNT_VALUE = 187.5  AND   AMOUNT_UNIT = 'mg';
UPDATE DS_STAGE   SET AMOUNT_VALUE = 700 WHERE DRUG_CONCEPT_CODE = '3584846'  AND   INGREDIENT_CONCEPT_CODE = '1023'  AND   BOX_SIZE = 30  AND   AMOUNT_VALUE = 200  AND   AMOUNT_UNIT = 'mg';
UPDATE DS_STAGE   SET AMOUNT_VALUE = 1.53 WHERE DRUG_CONCEPT_CODE = '5758486'  AND   INGREDIENT_CONCEPT_CODE = '29848'  AND   BOX_SIZE = 30  AND   AMOUNT_VALUE = 1.31  AND   AMOUNT_UNIT = 'mg';
--sometimes denominator is just a sum of components, so in this case we need to ignore denominators
update ds_stage 
 set 
amount_value = numerator_value,
amount_unit = numerator_unit,
numerator_value = '',
numerator_unit ='',
denominator_value ='',
denominator_unit =''
where 
drug_concept_code in (
select a.drug_concept_code from ds_stage a join 
(
select drug_concept_code, sum (numerator_value) as summ, NUMERATOR_UNIT from ds_stage group by drug_concept_code, denominator_value , denominator_unit, NUMERATOR_UNIT
) b on a.drug_concept_code = b.drug_concept_code and  summ / denominator_value < 1.2 and summ / denominator_value > 0.8
and a.numerator_unit = b.NUMERATOR_UNIT 
where a.NUMERATOR_UNIT = a.DENOMINATOR_UNIT
)
;
--drug with no din7
insert into ds_stage (DRUG_CONCEPT_CODE,INGREDIENT_CONCEPT_CODE,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT)
VALUES (60253264,612,'2.5','IU','1','ml');


update ds_stage
set numerator_value=numerator_value*10*DENOMINATOR_VALUE,
    numerator_unit='mg'
where NUMERATOR_UNIT='%';
update ds_stage 
set DENOMINATOR_VALUE=null,
    DENOMINATOR_UNIT=null
where DENOMINATOR_UNIT is not null and NUMERATOR_UNIT is null;

merge into ds_stage a 
using ds_stage_update b
on (a.drug_concept_code=b.drug_concept_code and a.ingredient_concept_code=b.ingredient_concept_code and a.box_size=b.box_size)
when matched then update set
a.AMOUNT_VALUE=b.AMOUNT_VALUE,
a.AMOUNT_UNIT=b.AMOUNT_UNIT,
a.NUMERATOR_VALUE=b.NUMERATOR_VALUE,
a.NUMERATOR_UNIT=b.NUMERATOR_UNIT,
a.DENOMINATOR_VALUE=b.DENOMINATOR_VALUE,
a.DENOMINATOR_UNIT=b.DENOMINATOR_UNIT
;
update ds_stage set NUMERATOR_VALUE=AMOUNT_VALUE*30,NUMERATOR_UNIT=AMOUNT_UNIT,DENOMINATOR_VALUE=30,DENOMINATOR_UNIT='ACTUAT', AMOUNT_VALUE=null,AMOUNT_UNIT=null
where drug_concept_code in ('2761996','3000459');
update ds_stage set NUMERATOR_VALUE=power(10,NUMERATOR_VALUE), NUMERATOR_UNIT='CCID_50' where NUMERATOR_UNIT='log CCID_50';
update ds_stage set NUMERATOR_VALUE=10 where drug_concept_code='5704697' and ingredient_concept_code='51742';
update ds_stage set NUMERATOR_VALUE=20 where drug_concept_code='5704711' and ingredient_concept_code='51742';
update ds_stage set NUMERATOR_VALUE=10 where drug_concept_code='5750852' and ingredient_concept_code='51742';
update ds_stage set NUMERATOR_VALUE=20 where drug_concept_code='5750875' and ingredient_concept_code='51742';
update ds_stage set NUMERATOR_VALUE=10 where drug_concept_code='5756211' and ingredient_concept_code='51742';
update ds_stage set NUMERATOR_VALUE=20 where drug_concept_code='5756228' and ingredient_concept_code='51742';
delete from ds_stage where ingredient_concept_code='3011' and amount_value='0';
--update dosages for inhalers
create table ds_inhaler as
with a as (
select DRUG_CONCEPT_CODE,INGREDIENT_CONCEPT_CODE,BOX_SIZE,AMOUNT_VALUE,AMOUNT_UNIT,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT,packaging,
trim(regexp_replace(regexp_substr(PACKAGING,'(\d*)(\s*) dose'),'dose')) as num_coef,regexp_replace(regexp_substr(PACKAGING,'\d* (plaquette|cartouche|flacon|inhalateur)'),'plaquette|cartouche|flacon|inhalateur') as box_coef
 from ds_stage a join packaging b on drug_concept_code=cast(din_7 as varchar(20)) where packaging like 'dose%inhal%' or packaging like '%inhal%dose%')
select distinct drug_concept_code,ingredient_concept_code, box_coef as box_size,' ' as AMOUNT_VALUE,' ' as AMOUNT_UNIT,a.AMOUNT_VALUE*num_coef as NUMERATOR_VALUE,a.AMOUNT_UNIT as NUMERATOR_UNIT, num_coef as DENOMINATOR_VALUE, 'ACTUAT' as DENOMINATOR_UNIT
 from a where num_coef is not null;
 insert into ds_inhaler (DRUG_CONCEPT_CODE,INGREDIENT_CONCEPT_CODE,BOX_SIZE,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT)
 values ('3812112','4179','1','12000','mcg','120','ACTUAT');
 insert into ds_inhaler (DRUG_CONCEPT_CODE,INGREDIENT_CONCEPT_CODE,BOX_SIZE,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT)
 values ('3812112','30613','1','720','mcg','120','ACTUAT');
  insert into ds_inhaler (DRUG_CONCEPT_CODE,INGREDIENT_CONCEPT_CODE,BOX_SIZE,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT)
 values ('3814128','4179','1','12000','mcg','120','ACTUAT');
  insert into ds_inhaler (DRUG_CONCEPT_CODE,INGREDIENT_CONCEPT_CODE,BOX_SIZE,NUMERATOR_VALUE,NUMERATOR_UNIT,DENOMINATOR_VALUE,DENOMINATOR_UNIT)
 values ('3814128','30613','1','720','mcg','120','ACTUAT'); 

merge into ds_stage a 
using ds_inhaler b
on (a.drug_concept_code=b.drug_concept_code and a.ingredient_concept_code=b.ingredient_concept_code)
when matched then update set
a.BOX_SIZE=b.BOX_SIZE,
a.AMOUNT_VALUE=null,
a.AMOUNT_UNIT=null,
a.NUMERATOR_VALUE=b.NUMERATOR_VALUE,
a.NUMERATOR_UNIT=b.NUMERATOR_UNIT,
a.DENOMINATOR_VALUE=b.DENOMINATOR_VALUE,
a.DENOMINATOR_UNIT=b.DENOMINATOR_UNIT
;
