"""
sources/surgery.py

Parses NAACCR surgery code tables from imsweb/algorithms GitHub repo:
  https://github.com/imsweb/algorithms/tree/master/src/main/resources/surgery/

Uses three XML files:
  2022  -> item 1290 (numeric codes: 00-99, classic pre-2023 format)
  2023  -> item 1291 A-codes (alphanumeric, 2023+ format for all 30 schemas)
  2024  -> item 1291 B-codes for 5 sites that changed again in 2024
           (Breast, Colon, Lung, Pancreas, Thyroid)

For the 25 unchanged schemas, 2023 and 2024 have identical A-codes so there
is no duplication.  For the 5 changed schemas both A-codes (2023) and B-codes
(2024) are kept as active standard concepts — they represent different
diagnosis-year cohorts.

"Concept replaced by" / "Replaces" relationships are generated by matching
descriptions within the same schema across transitions:
  1290 (2022) -> 1291 (2023 A-codes)
  1291 A-codes -> 1291 B-codes   (only for the 5 schemas that changed in 2024)
"""

import os
import re
import xml.etree.ElementTree as ET
import requests

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

GITHUB_RAW = (
    "https://raw.githubusercontent.com/imsweb/algorithms/master/"
    "src/main/resources/surgery"
)
CACHE_DIR = os.path.join(config.DOWNLOAD_DIR, "surgery")

ITEM_1290 = "1290"   # RX Summ--Surg Prim Site       (2003-2022, numeric codes)
ITEM_1291 = "1291"   # RX Summ--Surg Prim Site 2023  (2023+, alphanumeric codes)

# XML table titles that don't exactly match the DB Proc Schema concept_codes
TITLE_TO_SCHEMA = {
    "Bones, Joints, And Articular Cartilage":
        "Bones, Joints, and Soft Tissue",
    "Brain [and other parts of central nervous system]":
        "Brain",
    "Hematopoietic/Reticuloendothelial/ Immunoproliferative/Myeloproliferative Disease":
        "Hematopoietic",
    "Unknown and Ill-Defined Primary Sites":
        "Unknown And Ill-Defined Primary Sites",
}


# ── Download helpers ───────────────────────────────────────────────────────────

def _download_xml(year, verbose=False):
    """Download and cache surgery XML for given year. Returns parsed root element."""
    os.makedirs(CACHE_DIR, exist_ok=True)
    filename   = f"site-specific-surgery-tables-{year}.xml"
    cache_path = os.path.join(CACHE_DIR, filename)

    if not os.path.exists(cache_path):
        url = f"{GITHUB_RAW}/{filename}"
        if verbose:
            print(f"  Downloading {filename}...")
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        with open(cache_path, 'w', encoding='utf-8') as f:
            f.write(r.text)

    with open(cache_path, encoding='utf-8') as f:
        return ET.fromstring(f.read())


# ── Parsing helpers ────────────────────────────────────────────────────────────

def _clean_desc(text):
    """Strip inner HTML from description text and normalise whitespace."""
    if not text:
        return ""
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def _parse_table(xml_table):
    """
    Parse one <surgery-table> element.

    Returns (schema_code, [(code, description), ...])
    """
    title       = xml_table.attrib.get('title', '')
    schema_code = TITLE_TO_SCHEMA.get(title, title)

    rows = []
    for child in xml_table:
        if child.tag != 'row':
            continue
        code_el = child.find('code')
        desc_el = child.find('description')
        if code_el is None or not (code_el.text or '').strip():
            continue
        code = code_el.text.strip()
        desc = _clean_desc(desc_el.text if desc_el is not None else '')
        if code and desc:
            rows.append((code, desc))

    return schema_code, rows


def _build_lookup(root):
    """Return {schema_code: {code: description}} for all tables in an XML root."""
    lookup = {}
    for table in root:
        schema_code, rows = _parse_table(table)
        lookup[schema_code] = {code: desc for code, desc in rows}
    return lookup


# ── Main entry point ──────────────────────────────────────────────────────────

def fetch_all(verbose=True):
    """
    Build NAACCR Procedure concepts and replacement relationships.

    Returns
    -------
    concepts      : list of concept dicts  (NAACCR Procedure)
    relationships : list of relationship dicts
                    (Concept replaced by / Replaces across code generations)

    Date / status conventions
    -------------------------
    Generation       valid_start_date  valid_end_date  standard_concept  invalid_reason
    1290 replaced    1970-01-01        2022-12-31      None              U
    1290 no match    1970-01-01        2099-12-31      S                 None
    A-code -> B      2023-01-01        2023-12-31      None              U
    A-code kept      2023-01-01        2099-12-31      S                 None
    B-code (new)     2024-01-01        2099-12-31      S                 None

    1290 valid_start_date is left as 1970-01-01 so the ProcessManualConcepts
    NULL-coalesce logic preserves the existing DB value (which may be more
    precise).  For new A/B concepts we supply the correct year boundary.
    """
    if verbose:
        print("[surgery] Fetching surgery code tables...")

    root_2022 = _download_xml(2022, verbose)
    root_2023 = _download_xml(2023, verbose)
    root_2024 = _download_xml(2024, verbose)

    lkp_2022 = _build_lookup(root_2022)
    lkp_2023 = _build_lookup(root_2023)
    lkp_2024 = _build_lookup(root_2024)

    if verbose:
        n_codes = (
            sum(len(v) for v in lkp_2022.values()),
            sum(len(v) for v in lkp_2023.values()),
            sum(len(v) for v in lkp_2024.values()),
        )
        print(f"  2022 (item {ITEM_1290}): {len(lkp_2022)} schemas, {n_codes[0]} codes")
        print(f"  2023 (item {ITEM_1291}): {len(lkp_2023)} schemas, {n_codes[1]} codes")
        print(f"  2024 (item {ITEM_1291}): {len(lkp_2024)} schemas, {n_codes[2]} codes")

    # Use a dict keyed by concept_code so we can update dates/status after
    # the replacement pass determines which codes are superseded.
    concept_map   = {}   # concept_code -> concept dict
    relationships = []

    def _truncate(s, n=255):
        s = re.sub(r'\s+', ' ', s).strip()
        return s[:n - 3] + '...' if len(s) > n else s

    def _add_concept(schema, item_num, code, desc,
                     valid_start, valid_end, standard_concept, invalid_reason):
        cc = f"{schema}@{item_num}@{code}"
        if cc in concept_map:
            return
        concept_map[cc] = {
            'concept_code':     cc,
            'concept_name':     _truncate(f"{schema}@{desc}"),
            'concept_class_id': config.CLASS_PROCEDURE,
            'domain_id':        'Procedure',
            'vocabulary_id':    config.VOCABULARY_ID,
            'standard_concept': standard_concept,
            'valid_start_date': valid_start,
            'valid_end_date':   valid_end,
            'invalid_reason':   invalid_reason,
        }

    def _deprecate(schema, item_num, code, valid_end):
        """Mark an existing concept as deprecated (upgraded)."""
        cc = f"{schema}@{item_num}@{code}"
        if cc in concept_map:
            concept_map[cc]['standard_concept'] = None
            concept_map[cc]['valid_end_date']   = valid_end
            concept_map[cc]['invalid_reason']   = 'U'

    def _add_replacement(old_schema, old_item, old_code,
                         new_schema, new_item, new_code):
        old_cc = f"{old_schema}@{old_item}@{old_code}"
        new_cc = f"{new_schema}@{new_item}@{new_code}"
        relationships.append({
            'concept_code_1': old_cc,
            'concept_code_2': new_cc,
            'relationship_id': 'Concept replaced by',
        })
        relationships.append({
            'concept_code_1': new_cc,
            'concept_code_2': old_cc,
            'relationship_id': 'Replaces',
        })

    all_schemas = sorted(set(lkp_2022) | set(lkp_2023) | set(lkp_2024))
    unmatched_replacements = []

    for schema in all_schemas:
        codes_2022 = lkp_2022.get(schema, {})
        codes_2023 = lkp_2023.get(schema, {})
        codes_2024 = lkp_2024.get(schema, {})

        # ── 1290 concepts (2022) — start active; deprecation pass below ────────
        for code, desc in codes_2022.items():
            _add_concept(schema, ITEM_1290, code, desc,
                         valid_start='1970-01-01', valid_end='2099-12-31',
                         standard_concept='S', invalid_reason=None)

        # ── 1291 concepts (2023 + 2024, deduplicated) ─────────────────────────
        # For 25 unchanged schemas: 2023 == 2024, so updating dict is a no-op.
        # For 5 changed schemas: 2023 has A-codes, 2024 has B-codes (no overlap).
        all_1291 = dict(codes_2023)
        for code, desc in codes_2024.items():
            if code not in all_1291:
                all_1291[code] = desc

        for code, desc in codes_2023.items():
            # A-codes: start active; deprecation pass will downgrade those
            # that acquire a B-code replacement.
            _add_concept(schema, ITEM_1291, code, desc,
                         valid_start='2023-01-01', valid_end='2099-12-31',
                         standard_concept='S', invalid_reason=None)

        for code, desc in codes_2024.items():
            if code not in codes_2023:   # genuine B-codes (new in 2024)
                _add_concept(schema, ITEM_1291, code, desc,
                             valid_start='2024-01-01', valid_end='2099-12-31',
                             standard_concept='S', invalid_reason=None)

        # ── Replacement relationships + deprecation ───────────────────────────
        # No chaining: every old code points directly to the DEFINITIVE current
        # code (the end of the chain), so there are never double hops.
        #
        # For the 25 unchanged schemas: 2023 A-codes == 2024 A-codes.
        #   definitive 1291 code = the A-code.
        #   1290 -> A-code  (single hop)
        #
        # For the 5 schemas where 2024 replaced 2023 A-codes with B-codes:
        #   definitive 1291 code = the B-code (2024).
        #   1290   -> B-code  (single hop, skipping the intermediate A-code)
        #   A-code -> B-code  (single hop)

        schema_changed = set(codes_2023.keys()) != set(codes_2024.keys())

        # Build desc -> definitive 1291 code:
        #   If schema changed, prefer the 2024 B-code; fall back to 2023 A-code.
        #   If schema unchanged, 2023 == 2024 so either works.
        desc_to_definitive = {}
        for code, desc in codes_2023.items():
            desc_to_definitive[desc.lower()] = code
        if schema_changed:
            for code, desc in codes_2024.items():
                desc_to_definitive[desc.lower()] = code

        # 1290 -> definitive 1291
        for old_code, old_desc in codes_2022.items():
            new_code = desc_to_definitive.get(old_desc.lower())
            if new_code:
                _add_replacement(schema, ITEM_1290, old_code,
                                  schema, ITEM_1291, new_code)
                _deprecate(schema, ITEM_1290, old_code, valid_end='2022-12-31')
            else:
                unmatched_replacements.append(
                    (schema, ITEM_1290, old_code, old_desc[:60]))

        # 1291 A-code -> 1291 B-code (only for changed schemas)
        if schema_changed:
            desc_to_2024 = {d.lower(): c for c, d in codes_2024.items()}
            for a_code, a_desc in codes_2023.items():
                b_code = desc_to_2024.get(a_desc.lower())
                if b_code and b_code != a_code:
                    _add_replacement(schema, ITEM_1291, a_code,
                                      schema, ITEM_1291, b_code)
                    _deprecate(schema, ITEM_1291, a_code, valid_end='2023-12-31')

    concepts = list(concept_map.values())

    if verbose:
        from collections import Counter
        replacement_pairs = len(relationships) // 2
        sc_counts = Counter(c['standard_concept'] for c in concepts)
        print(f"[surgery] {len(concepts)} procedure concepts  "
              f"(S={sc_counts.get('S',0)}, deprecated={sc_counts.get(None,0)})")
        print(f"[surgery] {replacement_pairs} replacement pairs "
              f"({len(unmatched_replacements)} 1290 codes with no 1291 match)")
        if unmatched_replacements:
            print("  Sample unmatched 1290->1291 (first 5):")
            for schema, item, code, desc in unmatched_replacements[:5]:
                print(f"    {schema}@{item}@{code}  \"{desc}\"")

    return concepts, relationships


if __name__ == "__main__":
    concepts, relationships = fetch_all(verbose=True)
    print(f"\nSample concepts:")
    for c in concepts[:5]:
        print(f"  {c['concept_code']:<45} {c['concept_name'][:60]}")
    print(f"\nSample relationships:")
    for r in relationships[:6]:
        print(f"  {r['concept_code_1']:<45} {r['relationship_id']} {r['concept_code_2']}")
