CREATE TABLE SCT2_RELA_FULL_INT
(
   ID                     INTEGER,
   EFFECTIVETIME          VARCHAR2 (8 BYTE),
   ACTIVE                 VARCHAR2 (1 BYTE),
   MODULEID               VARCHAR2 (256 BYTE),
   SOURCEID               VARCHAR2 (256 BYTE),
   DESTINATIONID          VARCHAR2 (256 BYTE),
   RELATIONSHIPGROUP      INTEGER,
   TYPEID                 INTEGER,
   CHARACTERISTICTYPEID   VARCHAR2 (256 BYTE),
   MODIFIERID             VARCHAR2 (256 BYTE)
);

CREATE TABLE SCT2_DESC_FULL_EN_INT
(
   ID                   INTEGER,
   EFFECTIVETIME        VARCHAR2 (8 BYTE),
   ACTIVE               VARCHAR2 (1 BYTE),
   MODULEID             VARCHAR2 (18 BYTE),
   CONCEPTID            VARCHAR2 (256 BYTE),
   LANGUAGECODE         VARCHAR2 (2 BYTE),
   TYPEID               VARCHAR2 (18 BYTE),
   TERM                 VARCHAR2 (256 BYTE),
   CASESIGNIFICANCEID   VARCHAR2 (256 BYTE)
);

CREATE TABLE SCT2_CONCEPT_FULL_INT
(
   ID              VARCHAR2 (18 BYTE),
   EFFECTIVETIME   VARCHAR2 (8 BYTE),
   ACTIVE          VARCHAR2 (1 BYTE),
   MODULEID        VARCHAR2 (18 BYTE),
   STATUSID        VARCHAR2 (256 BYTE)
);

CREATE INDEX X_CID
   ON SCT2_CONCEPT_FULL_INT (ID);

CREATE INDEX X_rel_id
   ON SCT2_RELA_FULL_INT (ID);

CREATE INDEX X_DESC_2CD
   ON SCT2_DESC_FULL_EN_INT (CONCEPTID, MODULEID);

CREATE INDEX X_DESC_3CD
   ON SCT2_DESC_FULL_EN_INT (CONCEPTID, MODULEID, TERM);

CREATE TABLE SCT2_RELA_FULL_UK
(
   ID                     INTEGER,
   EFFECTIVETIME          VARCHAR2 (8 BYTE),
   ACTIVE                 VARCHAR2 (1 BYTE),
   MODULEID               VARCHAR2 (256 BYTE),
   SOURCEID               VARCHAR2 (256 BYTE),
   DESTINATIONID          VARCHAR2 (256 BYTE),
   RELATIONSHIPGROUP      INTEGER,
   TYPEID                 INTEGER,
   CHARACTERISTICTYPEID   VARCHAR2 (256 BYTE),
   MODIFIERID             VARCHAR2 (256 BYTE)
);

CREATE TABLE SCT2_DESC_FULL_UK
(
   ID                   INTEGER,
   EFFECTIVETIME        VARCHAR2 (8 BYTE),
   ACTIVE               VARCHAR2 (1 BYTE),
   MODULEID             VARCHAR2 (18 BYTE),
   CONCEPTID            VARCHAR2 (256 BYTE),
   LANGUAGECODE         VARCHAR2 (2 BYTE),
   TYPEID               VARCHAR2 (18 BYTE),
   TERM                 VARCHAR2 (256 BYTE),
   CASESIGNIFICANCEID   VARCHAR2 (256 BYTE)
);

CREATE TABLE SCT2_CONCEPT_FULL_UK
(
   ID              VARCHAR2 (18 BYTE),
   EFFECTIVETIME   VARCHAR2 (8 BYTE),
   ACTIVE          VARCHAR2 (1 BYTE),
   MODULEID        VARCHAR2 (18 BYTE),
   STATUSID        VARCHAR2 (256 BYTE)
);

CREATE INDEX X_rel_id_uk
   ON SCT2_RELA_FULL_UK (ID);

CREATE INDEX X_DESC_2CD_UK
   ON SCT2_DESC_FULL_UK (CONCEPTID, MODULEID);

CREATE INDEX X_DESC_3CD_UK
   ON SCT2_DESC_FULL_UK (CONCEPTID, MODULEID, TERM);

CREATE INDEX X_CID_UK
   ON SCT2_CONCEPT_FULL_UK (ID);
   
   CREATE TABLE CONCEPT_SYNONYM_STAGE
(
  SYNONYM_CONCEPT_ID    INTEGER,
  SYNONYM_NAME          VARCHAR2(1000 CHAR)     NOT NULL,
  SYNONYM_CONCEPT_CODE  VARCHAR2(50 CHAR)       NOT NULL,
  LANGUAGE_CONCEPT_ID   INTEGER                 NOT NULL
);

CREATE TABLE MRCONSO
(
  CUI       CHAR(8 CHAR)                        NOT NULL,
  LAT       CHAR(3 CHAR)                        NOT NULL,
  TS        CHAR(1 CHAR)                        NOT NULL,
  LUI       VARCHAR2(10 CHAR)                   NOT NULL,
  STT       VARCHAR2(3 CHAR)                    NOT NULL,
  SUI       VARCHAR2(10 CHAR)                   NOT NULL,
  ISPREF    CHAR(1 CHAR)                        NOT NULL,
  AUI       VARCHAR2(9 CHAR)                    NOT NULL,
  SAUI      VARCHAR2(50 CHAR),
  SCUI      VARCHAR2(100 CHAR),
  SDUI      VARCHAR2(100 CHAR),
  SAB       VARCHAR2(40 CHAR)                   NOT NULL,
  TTY       VARCHAR2(40 CHAR)                   NOT NULL,
  CODE      VARCHAR2(100 CHAR)                  NOT NULL,
  STR       VARCHAR2(3000 CHAR)                 NOT NULL,
  SRL       INTEGER                             NOT NULL,
  SUPPRESS  CHAR(1 CHAR)                        NOT NULL,
  CVF       INTEGER
);

CREATE INDEX X_MRCONSO_CODE ON MRCONSO
(CODE);

CREATE INDEX X_MRCONSO_CUI ON MRCONSO
(CUI);

CREATE INDEX X_MRCONSO_LUI ON MRCONSO
(LUI);

CREATE UNIQUE INDEX X_MRCONSO_PK ON MRCONSO
(AUI);

CREATE INDEX X_MRCONSO_SAB_TTY ON MRCONSO
(SAB, TTY);

CREATE INDEX X_MRCONSO_SCUI ON MRCONSO
(SCUI);

CREATE INDEX X_MRCONSO_SDUI ON MRCONSO
(SDUI);

CREATE INDEX X_MRCONSO_STR ON MRCONSO
(STR);

CREATE INDEX X_MRCONSO_SUI ON MRCONSO
(SUI);

ALTER TABLE MRCONSO ADD (
  CONSTRAINT X_MRCONSO_PK
  PRIMARY KEY
  (AUI)
  USING INDEX X_MRCONSO_PK);
