/*
================================================================================
1- prepare tables for Universal Load Stage.sql
================================================================================

Purpose
-------
Prepare Cancer Modifier manual tables from curated CDE decisions generated by
the oncology mining workflow.

Inputs
------
- dev_cancer_modifier.cancer_modifier_cde
- concept
- concept_manual
- concept_relationship_manual

Notes
-----
Replace :your_vocabs with the source vocabularies included in the current CDE
review before running the script. The CDE table is reviewed at mapping-row grain:
one source concept may have multiple rows when it has multiple proposed targets.
Do not aggregate decision flags by source_concept_id.
================================================================================
*/

-- -----------------------------------------------------------------------------
-- Create CDE review table for curator decisions
-- Run this DDL before loading the reviewed spreadsheet. It is IF NOT EXISTS so
-- the transformation sections below can be re-run after data is loaded.
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS dev_cancer_modifier.cancer_modifier_cde;
CREATE TABLE IF NOT EXISTS dev_cancer_modifier.cancer_modifier_cde
(
    source_concept_code       text,
    source_concept_id         integer,
    max_record                integer,
    source_concept_name       text,
    source_domain_id          text,
    action_req                text,
    source_vocabulary_id      text,
    relationship_id           text,
    relationship_id_predicate text,
    decision                  bool,
    to_destandardize          bool,
    to_make_precoosrinated_source_pair          bool,
    create_standard           bool,
    comment                   text,
    target_concept_id         INT,
    target_concept_code       text,
    target_concept_name       text,
    target_concept_class_id   text,
    target_standard_concept   text,
    target_invalid_reason     text,
    target_domain_id          text,
    target_vocabulary_id      text
);


-- -----------------------------------------------------------------------------
-- Insert approved source destandardization rows into concept_manual
-- -----------------------------------------------------------------------------
INSERT INTO concept_manual AS cm (
    concept_name,
    domain_id,
    vocabulary_id,
    concept_class_id,
    standard_concept,
    concept_code,
    valid_start_date,
    valid_end_date,
    invalid_reason
)
SELECT DISTINCT ON (c.concept_code, c.vocabulary_id)
    c.concept_name,
    c.domain_id,
    c.vocabulary_id,
    c.concept_class_id,
    NULL AS standard_concept,
    c.concept_code,
    c.valid_start_date,
    c.valid_end_date,
    c.invalid_reason
FROM dev_cancer_modifier.cancer_modifier_cde cde
JOIN concept c
    ON c.concept_id = cde.source_concept_id
WHERE cde.decision::bool IS TRUE
  AND cde.to_destandardize::bool IS TRUE
and c.vocabulary_id IN (:your_vocabs)
ORDER BY
    c.concept_code,
    c.vocabulary_id
ON CONFLICT (concept_code, vocabulary_id)
DO UPDATE
SET standard_concept = NULL;


-- -----------------------------------------------------------------------------
-- Insert approved pre-coordinated pairs rows into concept_manual
-- The precoordinated pairs creation step is implements as a part of manual work for LOINC (summer2026 release) because of the cdm 5.4 vocabulary tables limitations to properly represent EAVs
-- -----------------------------------------------------------------------------
INSERT INTO concept_manual AS cm (
    concept_name,
    domain_id,
    vocabulary_id,
    concept_class_id,
    standard_concept,
    concept_code,
    valid_start_date,
    valid_end_date,
    invalid_reason
)
SELECT DISTINCT ON (cde.source_concept_code, cde.source_vocabulary_id)
    LEFT(TRIM(c.concept_name) || ': ' || TRIM(cc.concept_name), 255) as concept_name,
   COALESCE(NULLIF(c.domain_id, ''), 'Observation') as domain_id,
    c.vocabulary_id,
    'Precoordinated pair' as concept_class_id,
    NULL AS standard_concept,
    cde.source_concept_code as concept_code,
    CURRENT_DATE AS valid_start_date,
    TO_DATE('20991231','yyyymmdd') AS valid_end_date ,
    NULL as invalid_reason
FROM dev_cancer_modifier.cancer_modifier_cde cde
JOIN concept c
on split_part(cde.source_concept_code,'|',1)=c.concept_code
    and c.vocabulary_id=cde.source_vocabulary_id
JOIN concept cc
on split_part(cde.source_concept_code,'|',2)=cc.concept_code
    and c.vocabulary_id=cde.source_vocabulary_id
WHERE cde.decision::bool IS TRUE
  AND cde.to_make_precoosrinated_source_pair::bool IS TRUE
and c.vocabulary_id IN (:your_vocabs)
and cc.vocabulary_id=c.vocabulary_id
ORDER BY
    cde.source_concept_code,
    cde.source_vocabulary_id
;


-- Preserve existing manual standard_concept = 'X' rows while refreshing metadata.
UPDATE concept_manual cm
set concept_name=c.concept_name,
    valid_start_date = c.valid_start_date,valid_end_date =c.valid_end_date,invalid_reason=c.invalid_reason,standard_concept=c.standard_concept
FROM concept c
JOIN concept_manual d
on (c.concept_code,c.vocabulary_id) = (d.concept_code,d.vocabulary_id)
and d.standard_concept='X'
where (c.concept_code,c.vocabulary_id) =(cm.concept_code,cm.vocabulary_id)
and c.vocabulary_id IN (:your_vocabs)
;

-- -----------------------------------------------------------------------------
-- Insert approved mapping rows into concept_relationship_manual
-- Keep this row-level. A single source_concept_id may legitimately contribute
-- multiple approved mapping rows with different targets.
-- -----------------------------------------------------------------------------
WITH mapping_rows AS (
    SELECT
        c.concept_code AS concept_code_1,
        c.vocabulary_id AS vocabulary_id_1,
        a.relationship_id,
        COALESCE(cc.concept_code, cm_target.concept_code, a.target_concept_code) AS concept_code_2,
        COALESCE(cc.vocabulary_id, cm_target.vocabulary_id, a.target_vocabulary_id) AS vocabulary_id_2
    FROM dev_cancer_modifier.cancer_modifier_cde a
    JOIN concept c
        ON a.source_concept_id = c.concept_id
    LEFT JOIN concept cc
        ON a.target_concept_id::int = cc.concept_id
    LEFT JOIN concept_manual cm_target
        ON a.target_concept_id IS NULL
       AND cm_target.concept_code = a.target_concept_code
       AND cm_target.vocabulary_id = COALESCE(a.target_vocabulary_id, 'Cancer Modifier')
       AND a.create_standard IS TRUE
    WHERE a.decision IS TRUE
      AND a.relationship_id IN ('Maps to', 'Maps to value','Is a')
      AND c.concept_id > 0
)
INSERT INTO concept_relationship_manual (concept_code_1,vocabulary_id_1,relationship_id,valid_start_date,valid_end_date,invalid_reason,concept_code_2,vocabulary_id_2)
SELECT DISTINCT ON (concept_code_1, vocabulary_id_1, relationship_id, concept_code_2, vocabulary_id_2)
    concept_code_1,
    vocabulary_id_1,
    relationship_id,
    CURRENT_DATE AS valid_start_date,
    TO_DATE('2099-12-31','YYYY-MM-DD') AS valid_end_date,
    NULL AS invalid_reason,
    concept_code_2,
    vocabulary_id_2
FROM mapping_rows mr
WHERE concept_code_2 IS NOT NULL
  AND vocabulary_id_2 IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM concept_relationship_manual crm
      WHERE crm.concept_code_1 = mr.concept_code_1
        AND crm.vocabulary_id_1 = mr.vocabulary_id_1
        AND crm.relationship_id = mr.relationship_id
        AND crm.concept_code_2 = mr.concept_code_2
        AND crm.vocabulary_id_2 = mr.vocabulary_id_2
  )
ON CONFLICT (concept_code_1, vocabulary_id_1,relationship_id,concept_code_2,vocabulary_id_2)
DO UPDATE
SET invalid_reason = NULL;
;

-- -----------------------------------------------------------------------------
-- Update manual relationship for cases when mapping relationships should be explicitly deprecated
-- -----------------------------------------------------------------------------
INSERT INTO concept_relationship_manual (concept_code_1,
                                         concept_code_2,
                                         vocabulary_id_1,
                                         vocabulary_id_2,
                                         relationship_id,
                                         valid_start_date,
                                         valid_end_date,
                                         invalid_reason)
with expicit_deprecation AS (SELECT concept_code_1,
                                  concept_code_2,
                                  vocabulary_id_1,
                                  vocabulary_id_2,
                                  relationship_id,
                                  valid_start_date,
                                  CURRENT_DATE as valid_end_date,
                                  'D'          as invalid_reason
                           from devv5.base_concept_relationship_manual crm
                           WHERE crm.invalid_reason IS NULL
                             AND exists (SELECT 1
                                         FROM cancer_modifier_cde cde1
                                                  JOIN concept c1
                                                       ON cde1.source_concept_id = c1.concept_id
                                         WHERE (c1.concept_code, c1.vocabulary_id) =
                                               (crm.concept_code_1, crm.vocabulary_id_1)
                                           and cde1.relationship_id IN ('Maps to', 'Maps to value')
                                           and cde1.decision is true)
                             and crm.relationship_id IN ('Maps to', 'Maps to value')
                             and (crm.concept_code_1, crm.vocabulary_id_1) <> (crm.concept_code_2, crm.vocabulary_id_2)
                           UNION ALL
                           SELECT c.concept_code,
                                  cc.concept_code,
                                  c.vocabulary_id,
                                  cc.vocabulary_id,
                                  cr.relationship_id,
                                  cr.valid_start_date,
                                  CURRENT_DATE as valid_end_date,
                                  'D'          as invalid_reason
                           from concept_relationship cr
                                    JOIN concept c
                                         on c.concept_id = cr.concept_id_1
                                    JOIN concept cc
                                         on cc.concept_id = cr.concept_id_2
                           WHERE cr.invalid_reason IS NULL
                             AND exists (SELECT 1
                                         FROM cancer_modifier_cde cde1
                                         where cde1.source_concept_id = cr.concept_id_1
                                           and cde1.relationship_id IN ('Maps to', 'Maps to value')
                                           and cde1.decision is true)
                             and cr.relationship_id IN ('Maps to', 'Maps to value')
                             and cr.concept_id_1 != cr.concept_id_2)

SELECT *
from expicit_deprecation
;





