CREATE TABLE OPCS
(
   CUI    VARCHAR2 (50),
   TERM   VARCHAR2 (150)
);

CREATE TABLE OPCSSCTMAP
(
   SCUI     VARCHAR2 (5),
   STUI     VARCHAR2 (1),
   TCUI     VARCHAR2 (18),
   TTUI     VARCHAR2 (1),
   MAPTYP   VARCHAR2 (1)
);