--new concepts
--create table new_c0 as select * from new_c
;
drop table new_c
;
create table new_c as 
select * from concept 
where vocabulary_id ='PPI'
and (concept_code, concept_id, concept_name, concept_class_id, coalesce (standard_concept, 'X')) not in (
select  concept_code, concept_id, concept_name,concept_class_id, coalesce (standard_concept, 'X') from devv5.concept where vocabulary_id ='PPI')
order by concept_code desc
;
--affected relationships
drop table ppi_rel
;
create table ppi_rel as
with new_c as 
(
select concept_id from concept 
where vocabulary_id ='PPI'
)
select r.* from concept_relationship r
join new_c on concept_id_2 = new_c.concept_id 
union
select r.* from concept_relationship r
join new_c on concept_id_1 = new_c.concept_id 
;
drop table ppi_rel_old;
create table ppi_rel_old as
with new_c as 
(
select concept_id from devv5.concept 
where vocabulary_id ='PPI'
)
select r.* from devv5.concept_relationship r
join new_c on concept_id_2 = new_c.concept_id 
union
select r.* from devv5.concept_relationship r
join new_c on concept_id_1 = new_c.concept_id 
;
drop table new_r
;
create table new_r as
select * from ppi_rel 
where (concept_id_1, concept_id_2, relationship_id, valid_start_date, valid_end_date, coalesce (invalid_reason) ) not in (
select concept_id_1, concept_id_2, relationship_id, valid_start_date, valid_end_date, coalesce (invalid_reason) from ppi_rel_old)
;
drop table if exists covid_concepts
;
--get the top level Modules, so their concept_ids will be used in the scripts below
select * from concept where vocabulary_id ='PPI' and concept_class_id ='Module'
;
/*
1119621	Personal and Family Health History
1120003	COVID-19 Vaccine Survey
*/
create table covid_concepts as
select distinct a.* 
  from new_c a
left join concept_relationship r on a.concept_id = r.concept_id_1  and r.relationship_id ='Has PPI parent code'
left join concept_relationship r2 on r.concept_id_2 = r2.concept_id_1   and r2.relationship_id ='Has PPI parent code'
left join concept_relationship r3 on r2.concept_id_2 = r3.concept_id_1 and r3.relationship_id ='Has PPI parent code'
left join concept_relationship r4 on r3.concept_id_2 = r4.concept_id_1 and r4.relationship_id ='Has PPI parent code'
where 1120003 in (r4.concept_id_2,r3.concept_id_2,r2.concept_id_2,r.concept_id_2)
union
select * from new_c where concept_code ='cope_vaccine3'
;
drop table if exists hist_concepts
;
create table hist_concepts as
select distinct a.* 
  from new_c a
left join concept_relationship r on a.concept_id = r.concept_id_1  and r.relationship_id ='Has PPI parent code'
left join concept_relationship r2 on r.concept_id_2 = r2.concept_id_1   and r2.relationship_id ='Has PPI parent code'
left join concept_relationship r3 on r2.concept_id_2 = r3.concept_id_1 and r3.relationship_id ='Has PPI parent code'
left join concept_relationship r4 on r3.concept_id_2 = r4.concept_id_1 and r4.relationship_id ='Has PPI parent code'
where 1119621 in (r4.concept_id_2,r3.concept_id_2,r2.concept_id_2,r.concept_id_2)
union 
--get autogenerated PPI123 concepts 
select * from new_c where concept_code like 'PPI%'
;
select * from hist_concepts  --history concepts
;
select * from covid_concepts --covid concepts
;
select * from new_c where concept_id not in (select concept_id from covid_concepts union select concept_id from hist_concepts)
;
--COVID concepts relationships
drop table if exists history_rel
;
create table history_rel as
select * from new_r where concept_id_1 in (select concept_id from hist_concepts)
union
select * from new_r where concept_id_2 in (select concept_id from hist_concepts)
;
drop table if exists covid_rel
;
--hisory concepts relationships
create table covid_rel as
select * from new_r where concept_id_1 in (select concept_id from covid_concepts)
union
select * from new_r where concept_id_2 in (select concept_id from covid_concepts)
;
select * from history_rel
;
select * from covid_rel
