/**************************************************************************
* Copyright 2016 Observational Health Data Sciences and Informatics (OHDSI)
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
* 
* Authors: Timur Vakhitov, Christian Reich
* Date: 2017
**************************************************************************/

DROP TABLE IF EXISTS SOURCES.LOINC;
CREATE TABLE SOURCES.LOINC
(
  LOINC_NUM                  VARCHAR(10),
  COMPONENT                  VARCHAR(255),
  PROPERTY                   VARCHAR(30),
  TIME_ASPCT                 VARCHAR(15),
  SYSTEM                     VARCHAR(500),
  SCALE_TYP                  VARCHAR(30),
  METHOD_TYP                 VARCHAR(100),
  CLASS                      VARCHAR(50),
  VERSIONLASTCHANGED         VARCHAR(10),
  CHNG_TYPE                  VARCHAR(3),
  DEFINITIONDESCRIPTION      TEXT,
  STATUS                     VARCHAR(11),
  CONSUMER_NAME              VARCHAR(255),
  CLASSTYPE                  VARCHAR(20),
  FORMULA                    TEXT,
  SPECIES                    VARCHAR(20),
  EXMPL_ANSWERS              TEXT,
  SURVEY_QUEST_TEXT          TEXT,
  SURVEY_QUEST_SRC           VARCHAR(50),
  UNITSREQUIRED              VARCHAR(1),
  SUBMITTED_UNITS            VARCHAR(30),
  RELATEDNAMES2              TEXT,
  SHORTNAME                  VARCHAR(100),
  ORDER_OBS                  VARCHAR(15),
  CDISC_COMMON_TESTS         VARCHAR(1),
  HL7_FIELD_SUBFIELD_ID      VARCHAR(50),
  EXTERNAL_COPYRIGHT_NOTICE  TEXT,
  EXAMPLE_UNITS              VARCHAR(255),
  LONG_COMMON_NAME           VARCHAR(255),
  UNITSANDRANGE              TEXT,
  DOCUMENT_SECTION           VARCHAR(255),
  EXAMPLE_UCUM_UNITS         VARCHAR(255),
  EXAMPLE_SI_UCUM_UNITS      VARCHAR(255),
  STATUS_REASON              VARCHAR(9),
  STATUS_TEXT                TEXT,
  CHANGE_REASON_PUBLIC       TEXT,
  COMMON_TEST_RANK           VARCHAR(20),
  COMMON_ORDER_RANK          VARCHAR(20),
  COMMON_SI_TEST_RANK        VARCHAR(20),
  HL7_ATTACHMENT_STRUCTURE   VARCHAR(15),
  EXTERNAL_COPYRIGHT_LINK    VARCHAR(255),
  PANELTYPE                  VARCHAR(50),
  ASKATORDERENTRY            VARCHAR(255),
  ASSOCIATEDOBSERVATIONS     VARCHAR(255),
  VERSIONFIRSTRELEASED       VARCHAR(255),
  VALIDHL7ATTACHMENTREQUEST  VARCHAR(255),
  VOCABULARY_DATE            DATE,
  VOCABULARY_VERSION         VARCHAR (200)
);

DROP TABLE IF EXISTS SOURCES.MAP_TO;
CREATE TABLE SOURCES.MAP_TO
(
  LOINC           VARCHAR(10),
  MAP_TO          VARCHAR(10),
  MAP_TO_COMMENT  TEXT
);

DROP TABLE IF EXISTS SOURCES.SOURCE_ORGANIZATION;
CREATE TABLE SOURCES.SOURCE_ORGANIZATION
(
  ID            INT4,
  COPYRIGHT_ID  VARCHAR(255),
  NAME          VARCHAR(255),
  COPYRIGHT     TEXT,
  TERMS_OF_USE  TEXT,
  URL           VARCHAR(255)
);

DROP TABLE IF EXISTS SOURCES.LOINC_FORMS;
CREATE TABLE SOURCES.LOINC_FORMS
(
   PARENTLOINC   VARCHAR (10),
   LOINC         VARCHAR (10)
);

DROP TABLE IF EXISTS SOURCES.LOINC_CLASS;
CREATE TABLE SOURCES.LOINC_CLASS
(
  CONCEPT_ID        INT,
  CONCEPT_NAME      VARCHAR(256),
  DOMAIN_ID         VARCHAR(200),
  VOCABULARY_ID     VARCHAR(20),
  CONCEPT_CLASS_ID  VARCHAR(20),
  STANDARD_CONCEPT  VARCHAR(1),
  CONCEPT_CODE      VARCHAR(40),
  VALID_START_DATE  DATE,
  VALID_END_DATE    DATE,
  INVALID_REASON    VARCHAR(1)
);

DROP TABLE IF EXISTS SOURCES.CPT_MRSMAP;
CREATE TABLE SOURCES.CPT_MRSMAP
(
  MAPSETCUI  CHAR(8),
  MAPSETSAB  VARCHAR(40),
  MAPID      VARCHAR(50),
  MAPSID     VARCHAR(50),
  FROMEXPR   VARCHAR(4000),
  FROMTYPE   VARCHAR(50),
  REL        VARCHAR(4),
  RELA       VARCHAR(100),
  TOEXPR     VARCHAR(4000),
  TOTYPE     VARCHAR(50),
  CVF        INT,
  FILLER     INT
);

DROP TABLE IF EXISTS SOURCES.SCCCREFSET_MAPCORRORFULL_INT;
CREATE TABLE SOURCES.SCCCREFSET_MAPCORRORFULL_INT
(
   ID                      VARCHAR (256) NOT NULL,
   EFFECTIVETIME           VARCHAR (256) NOT NULL,
   ACTIVE                  INT4 NOT NULL,
   MODULEID                INT4,
   REFSETID                INT4,
   REFERENCEDCOMPONENTID   INT4 NOT NULL,
   MAPTARGET               VARCHAR (256) NOT NULL,
   EXPRESSION              VARCHAR (256),
   DEFINITIONSTATUSID      VARCHAR (256),
   CORRELATIONID           VARCHAR (256),
   CONTENTORIGINID         VARCHAR (256)
);

DROP TABLE IF EXISTS SOURCES.LOINC_HIERARCHY;
CREATE TABLE SOURCES.LOINC_HIERARCHY
(
  PATH_TO_ROOT      VARCHAR(256),
  SEQUENCE          VARCHAR(256),
  IMMEDIATE_PARENT  VARCHAR(256),
  CODE              VARCHAR(256),
  CODE_TEXT         VARCHAR(256)
);

DROP TABLE IF EXISTS SOURCES.LOINC_ANSWERSLIST;
CREATE TABLE SOURCES.LOINC_ANSWERSLIST
(
  ANSWERLISTID                     VARCHAR(1000),
  ANSWERLISTNAME                   VARCHAR(1000),
  ANSWERLISTOID                    VARCHAR(1000),
  EXTDEFINEDYN                     VARCHAR(1000),
  EXTDEFINEDANSWERLISTCODESYSTEM   VARCHAR(1000),
  EXTDEFINEDANSWERLISTLINK         VARCHAR(1000),
  ANSWERSTRINGID                   VARCHAR(1000),
  LOCALANSWERCODE                  VARCHAR(1000),
  LOCALANSWERCODESYSTEM            VARCHAR(1000),
  SEQUENCENUMBER                   VARCHAR(1000),
  DISPLAYTEXT                      VARCHAR(1000),
  EXTCODEID                        VARCHAR(1000),
  EXTCODEDISPLAYNAME               VARCHAR(1000),
  EXTCODESYSTEM                    VARCHAR(1000),
  EXTCODESYSTEMVERSION             VARCHAR(1000),
  EXTCODESYSTEMCOPYRIGHTNOTICE     VARCHAR(1000),
  SUBSEQUENTTEXTPROMPT             VARCHAR(1000),
  DESCRIPTION                      VARCHAR(1000),
  SCORE                            VARCHAR(1000)
);

DROP TABLE IF EXISTS SOURCES.LOINC_ANSWERSLISTLINK;
CREATE TABLE SOURCES.LOINC_ANSWERSLISTLINK
(
  LOINCNUMBER         VARCHAR(1000),
  LONGCOMMONNAME      VARCHAR(1000),
  ANSWERLISTID        VARCHAR(1000),
  ANSWERLISTNAME      VARCHAR(1000),
  ANSWERLISTLINKTYPE  VARCHAR(1000),
  APPLICABLECONTEXT   VARCHAR(1000)
);

CREATE OR REPLACE FUNCTION sources.py_xlsparse_forms(xls_path varchar)
RETURNS
TABLE (
    ParentLoinc varchar,
    Loinc varchar
)
AS
$BODY$
import xlrd
res = []
wb = xlrd.open_workbook(xls_path)
sheet = wb.sheet_by_name('FORMS')
for rowid in range(1,sheet.nrows):
  row = sheet.row_values(rowid, end_colx=6)
  ParentLoinc=row[1] if row[1] else None
  Loinc=row[5] if row[5] else None
  res.append((ParentLoinc,Loinc))
return res
$BODY$
LANGUAGE 'plpythonu'
SECURITY DEFINER;