CREATE TABLE LOINC
(
  LOINC_NUM                  VARCHAR2(10),
  COMPONENT                  VARCHAR2(255),
  PROPERTY                   VARCHAR2(30),
  TIME_ASPCT                 VARCHAR2(15),
  SYSTEM                     VARCHAR2(100),
  SCALE_TYP                  VARCHAR2(30),
  METHOD_TYP                 VARCHAR2(50),
  CLASS                      VARCHAR2(20),
  SOURCE                     VARCHAR2(8),
  DATE_LAST_CHANGED          DATE,
  CHNG_TYPE                  VARCHAR2(3),
  COMMENTS                   CLOB,
  STATUS                     VARCHAR2(11),
  CONSUMER_NAME              VARCHAR2(255),
  MOLAR_MASS                 VARCHAR2(13),
  CLASSTYPE                  VARCHAR2(20),
  FORMULA                    VARCHAR2(255),
  SPECIES                    VARCHAR2(20),
  EXMPL_ANSWERS              CLOB,
  ACSSYM                     CLOB,
  BASE_NAME                  VARCHAR2(50),
  NAACCR_ID                  VARCHAR2(20),
  CODE_TABLE                 VARCHAR2(10),
  SURVEY_QUEST_TEXT          CLOB,
  SURVEY_QUEST_SRC           VARCHAR2(50),
  UNITSREQUIRED              VARCHAR2(1),
  SUBMITTED_UNITS            VARCHAR2(30),
  RELATEDNAMES2              CLOB,
  SHORTNAME                  VARCHAR2(40),
  ORDER_OBS                  VARCHAR2(15),
  CDISC_COMMON_TESTS         VARCHAR2(1),
  HL7_FIELD_SUBFIELD_ID      VARCHAR2(50),
  EXTERNAL_COPYRIGHT_NOTICE  CLOB,
  EXAMPLE_UNITS              VARCHAR2(255),
  LONG_COMMON_NAME           VARCHAR2(255),
  HL7_V2_DATATYPE            VARCHAR2(255),
  HL7_V3_DATATYPE            VARCHAR2(255),
  CURATED_RANGE_AND_UNITS    CLOB,
  DOCUMENT_SECTION           VARCHAR2(255),
  EXAMPLE_UCUM_UNITS         VARCHAR2(255),
  EXAMPLE_SI_UCUM_UNITS      VARCHAR2(255),
  STATUS_REASON              VARCHAR2(9),
  STATUS_TEXT                CLOB,
  CHANGE_REASON_PUBLIC       CLOB,
  COMMON_TEST_RANK           VARCHAR2(20),
  COMMON_ORDER_RANK          VARCHAR2(20),
  COMMON_SI_TEST_RANK        VARCHAR2(20),
  HL7_ATTACHMENT_STRUCTURE   VARCHAR2(15)
);

CREATE TABLE MAP_TO
(
  LOINC      VARCHAR2(10),
  MAP_TO     VARCHAR2(10),
  "COMMENT"  CLOB
);

CREATE TABLE SOURCE_ORGANIZATION
(
  COPYRIGHT_ID	VARCHAR2(255),
  NAME          VARCHAR2(255),
  COPYRIGHT     CLOB,
  TERMS_OF_USE  CLOB,
  URL           VARCHAR2(255)
);

CREATE TABLE LOINC_ANSWERS
(
  LOINC                   VARCHAR2(10 BYTE),
  LOINCNAME               VARCHAR2(255 BYTE),
  ANSWERLISTOID           VARCHAR2(255 BYTE),
  EXTERNALLYDEFINEDYN     VARCHAR2(1 BYTE),
  EXTERNALLYDEFINEDANSCS  VARCHAR2(255 BYTE),
  LINKTOEXTERNALLIST      VARCHAR2(255 BYTE),
  ANSWERSTRINGID          VARCHAR2(255 BYTE),
  ANSWERCODE              VARCHAR2(255 BYTE),
  SEQUENCENO              VARCHAR2(255 BYTE),
  DISPLAYTEXT             VARCHAR2(255 BYTE),
  ANSWERCODESYSTEM        VARCHAR2(255 BYTE),
  GLOBALID                VARCHAR2(255 BYTE),
  GLOBALIDCODESYSTEM      VARCHAR2(255 BYTE),
  COPYRIGHTNOTICE         VARCHAR2(255 BYTE),
  DESCRIPTION             VARCHAR2(255 BYTE),
  SCORE                   VARCHAR2(255 BYTE)
);

CREATE TABLE LOINC_CLASS
(
  CONCEPT_ID        INTEGER,
  CONCEPT_NAME      VARCHAR2(256 BYTE),
  DOMAIN_ID         VARCHAR2(200 BYTE),
  VOCABULARY_ID     VARCHAR2(20 BYTE),
  CONCEPT_CLASS_ID  VARCHAR2(20 BYTE),
  STANDARD_CONCEPT  VARCHAR2(1 BYTE),
  CONCEPT_CODE      VARCHAR2(40 BYTE),
  VALID_START_DATE  DATE,
  VALID_END_DATE    DATE,
  INVALID_REASON    VARCHAR2(1 BYTE)
);

CREATE TABLE CPT_MRSMAP
(
  MAPSETCUI  CHAR(8 BYTE),
  MAPSETSAB  VARCHAR2(40 BYTE),
  MAPID      VARCHAR2(50 BYTE),
  MAPSID     VARCHAR2(50 BYTE),
  FROMEXPR   VARCHAR2(4000 BYTE),
  FROMTYPE   VARCHAR2(50 BYTE),
  REL        VARCHAR2(4 BYTE),
  RELA       VARCHAR2(100 BYTE),
  TOEXPR     VARCHAR2(4000 BYTE),
  TOTYPE     VARCHAR2(50 BYTE),
  CVF        INTEGER
);

CREATE TABLE scccRefset_MapCorrOrFull_INT
(
   ID                      VARCHAR (256) NOT NULL,
   EFFECTIVETIME           VARCHAR (256) NOT NULL,
   ACTIVE                  NUMBER NOT NULL,
   MODULEID                NUMBER,
   REFSETID                NUMBER,
   REFERENCEDCOMPONENTID   NUMBER NOT NULL,
   MAPTARGET               VARCHAR (256) NOT NULL
);
