OPTIONS (errors=0, direct=true)
LOAD DATA 
CHARACTERSET UTF8 LENGTH SEMANTICS CHAR
INFILE 'CMS32_DESC_LONG_SG.txt'
BADFILE 'CMS_DESC_LONG_SG.bad'
DISCARDFILE 'CMS_DESC_LONG_SG.dsc'
TRUNCATE
INTO TABLE CMS_DESC_LONG_SG
(
	CODE position(1:4), 
	NAME position(6:263) 
)