CREATE TABLE CMS_DESC_LONG_SG
(
   code   VARCHAR2 (8) NOT NULL,
   name   VARCHAR2 (256) NOT NULL,
   PRIMARY KEY (code)
);

CREATE TABLE CMS_DESC_SHORT_SG
(
   code   VARCHAR2 (8) NOT NULL,
   name   VARCHAR2 (256) NOT NULL,
   PRIMARY KEY (code)
);
