/**************************************************************************
* Copyright 2016 Observational Health Data Sciences and Informatics (OHDSI)
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*Author: Anna Ostropolets
**************************************************************************/

--CREATING TABLES FOR ORIGINAL DATA
DROP TABLE IF EXISTS SOURCES.DPD_DRUG_ALL;CREATE TABLE SOURCES.DPD_DRUG_ALL(   DRUG_CODE                   INT4 NOT NULL,   PRODUCT_CATEGORIZATION      VARCHAR(80),   CLASS                       VARCHAR(40),   DRUG_IDENTIFICATION_NUMBER  VARCHAR(200),   BRAND_NAME                  VARCHAR(200),   DESCRIPTOR                  VARCHAR(200),   PEDIATRIC_FLAG              VARCHAR(1),   ACCESSION_NUMBER            VARCHAR(5),   NUMBER_OF_AIS               VARCHAR(10),   LAST_UPDATE_DATE            DATE,   AI_GROUP_NO                 VARCHAR(10),
   FILLER_COLUMN1              TEXT,
   FILLER_COLUMN2              TEXT,
   FILLER_COLUMN3              TEXT);

DROP TABLE IF EXISTS SOURCES.DPD_ACTIVE_INGREDIENTS_ALL;CREATE TABLE SOURCES.DPD_ACTIVE_INGREDIENTS_ALL(   DRUG_CODE                INT4 NOT NULL,   ACTIVE_INGREDIENT_CODE   INT4,   INGREDIENT               VARCHAR(240),   INGREDIENT_SUPPLIED_IND  VARCHAR(1),   STRENGTH                 VARCHAR(20),   STRENGTH_UNIT            VARCHAR(40),   STRENGTH_TYPE            VARCHAR(40),   DOSAGE_VALUE             VARCHAR(20),   BASE                     VARCHAR(1),   DOSAGE_UNIT              VARCHAR(40),   NOTES                    VARCHAR(2000),
   FILLER_COLUMN1           TEXT,
   FILLER_COLUMN2           TEXT,
   FILLER_COLUMN3           TEXT,
   FILLER_COLUMN4           TEXT);
DROP TABLE IF EXISTS SOURCES.DPD_FORM_ALL;
CREATE TABLE SOURCES.DPD_FORM_ALL
(
   DRUG_CODE            INT4 NOT NULL,
   PHARM_FORM_CODE      INT4,
   PHARMACEUTICAL_FORM  VARCHAR(100),
   FILLER_COLUMN1       TEXT,
   VOCABULARY_DATE      DATE,
   VOCABULARY_VERSION   VARCHAR (200)
);

DROP TABLE IF EXISTS SOURCES.DPD_ROUTE_ALL;
CREATE TABLE SOURCES.DPD_ROUTE_ALL
(
   DRUG_CODE                     INT4 NOT NULL,
   ROUTE_OF_ADMINISTRATION_CODE  INT4,
   ROUTE_OF_ADMINISTRATION       VARCHAR(50),
   FILLER_COLUMN1                TEXT
);

DROP TABLE IF EXISTS SOURCES.DPD_PACKAGING_ALL;CREATE TABLE SOURCES.DPD_PACKAGING_ALL(   DRUG_CODE            INT4 NOT NULL,   UPC                  VARCHAR(12),   PACKAGE_SIZE_UNIT    VARCHAR(40),   PACKAGE_TYPE         VARCHAR(40),   PACKAGE_SIZE         VARCHAR(5),   PRODUCT_INFORMATION  VARCHAR(80),
   FILLER_COLUMN1       TEXT,
   FILLER_COLUMN2       TEXT);
DROP TABLE IF EXISTS SOURCES.DPD_STATUS_ALL;CREATE TABLE SOURCES.DPD_STATUS_ALL(   DRUG_CODE            INT4 NOT NULL,   CURRENT_STATUS_FLAG  VARCHAR(255),   STATUS               VARCHAR(255),   HISTORY_DATE         DATE,
   FILLER_COLUMN1       TEXT,
   FILLER_COLUMN2       TEXT,
   FILLER_COLUMN3       TEXT);
DROP TABLE IF EXISTS SOURCES.DPD_COMPANIES_ALL;CREATE TABLE SOURCES.DPD_COMPANIES_ALL(   DRUG_CODE                  INT4 NOT NULL,   MFR_CODE                   VARCHAR(15),   COMPANY_CODE               INT4,   COMPANY_NAME               VARCHAR(80),   COMPANY_TYPE               VARCHAR(40),   ADDRESS_MAILING_FLAG       VARCHAR(1),   ADDRESS_BILLING_FLAG       VARCHAR(1),   ADDRESS_NOTIFICATION_FLAG  VARCHAR(1),   ADDRESS_OTHER              VARCHAR(1),   SUITE_NUMBER               VARCHAR(50),   STREET_NAME                VARCHAR(80),   CITY_NAME                  VARCHAR(60),   PROVINCE                   VARCHAR(40),   COUNTRY                    VARCHAR(40),   POSTAL_CODE                VARCHAR(20),   POST_OFFICE_BOX            VARCHAR(25),
   FILLER_COLUMN1             TEXT,
   FILLER_COLUMN2             TEXT);
DROP TABLE IF EXISTS SOURCES.DPD_THERAPEUTIC_CLASS_ALL;CREATE TABLE SOURCES.DPD_THERAPEUTIC_CLASS_ALL(   DRUG_CODE       INT4 NOT NULL,   TC_ATC_NUMBER   VARCHAR(8),   TC_ATC          VARCHAR(120),   TC_AHFS_NUMBER  VARCHAR(20),   TC_AHFS         VARCHAR(80),
   FILLER_COLUMN1  TEXT,
   FILLER_COLUMN2  TEXT);--CREATE MANUAL TABLES (previous and new data)DROP TABLE IF EXISTS NEW_PACK;
CREATE TABLE NEW_PACK(   CONCEPT_CODE       VARCHAR(30),   AIC                VARCHAR(240),   CONCEPT_NAME       VARCHAR(240),   INGREDIENT         VARCHAR(240),   AMOUNT_VALUE       VARCHAR(20),   AMOUNT_UNIT        VARCHAR(40),   DENOMINATOR_VALUE  VARCHAR(40),   DENOMINATOR_UNIT   VARCHAR(40),   NUMERATOR_VALUE    VARCHAR(20),   NUMERATOR_UNIT     VARCHAR(40),   NOTES              VARCHAR(2000),   DRUG_CODE          VARCHAR(10),   BRAND_NAME         VARCHAR(200),   NUMBER_OF_AIS      VARCHAR(10),   INVALID_REASON     VARCHAR(1));
DROP TABLE IF EXISTS PACK_FORM;CREATE TABLE PACK_FORM(   CONCEPT_NAME_1       VARCHAR(255),   CONCEPT_NAME_2       VARCHAR(255));
DROP TABLE IF EXISTS PC_STAGE_MANUAL;CREATE TABLE PC_STAGE_MANUAL(   CONCEPT_NAME_1       VARCHAR(255),   CONCEPT_NAME_2       VARCHAR(1255),   AMOUNT               INT4,   BOX_SIZE             INT4);
DROP TABLE IF EXISTS NEW_RTC;CREATE TABLE NEW_RTC (  CONCEPT_NAME_1       VARCHAR(255),  CONCEPT_CLASS_ID_1   VARCHAR(255),  CONCEPT_ID_2         INT4,  CONCEPT_NAME_2       VARCHAR(255),  INVALID_REASON_2     VARCHAR(255),  PRECEDENCE           INT4,  CONVERSION_FACTOR    FLOAT);
DROP TABLE IF EXISTS PREV_RTC;
CREATE TABLE PREV_RTC
(
   CONCEPT_CODE_1      VARCHAR(255),
   CONCEPT_NAME_1      VARCHAR(255),
   CONCEPT_CLASS_ID_1  VARCHAR(255),
   CONCEPT_CODE_2      VARCHAR(255),
   CONCEPT_NAME_2      VARCHAR(255),
   CONCEPT_CLASS_ID_2  VARCHAR(255),
   CONCEPT_ID_2        INT4,
   INVALID_REASON_2    VARCHAR(1),
   PRECEDENCE          INT4,
   CONVERSION_FACTOR   FLOAT
);
