/**************************************************************************
* Copyright 2016 Observational Health Data Sciences and Informatics (OHDSI)
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
**************************************************************************/


--SEQUENCE FOR OMOP-GENERATED CODES STARTING WITH THE LAST CODE USED IN PREVIOUS VOCABULARY
CREATE SEQUENCE CONC_STAGE_SEQ 
  MINVALUE 97124
  MAXVALUE 1000000
  START WITH 97124
  INCREMENT BY 1
  CACHE 20;
  ;

--CREATING TABLES FOR ORIGINAL DATA
CREATE TABLE DRUG_IA
(
   DRUG_CODE                   NUMBER               NOT NULL,
   PRODUCT_CATEGORIZATION      VARCHAR2(80 BYTE),
   CLASS                       VARCHAR2(40 BYTE),
   DRUG_IDENTIFICATION_NUMBER   VARCHAR2(200 BYTE),
   BRAND_NAME                  VARCHAR2(200 BYTE),
   DESCRIPTOR                  VARCHAR2(200 BYTE),
   PEDIATRIC_FLAG              VARCHAR2(1 BYTE),
   ACCESSION_NUMBER            VARCHAR2(5 BYTE),
   NUMBER_OF_AIS               VARCHAR2(10 BYTE),
   LAST_UPDATE_DATE            DATE,
   AI_GROUP_NO                 VARCHAR2(10 BYTE)
);

CREATE TABLE DRUG_ACT
(
   DRUG_CODE                   NUMBER               NOT NULL,
   PRODUCT_CATEGORIZATION      VARCHAR2(80 BYTE),
   CLASS                       VARCHAR2(40 BYTE),
   DRUG_IDENTIFICATION_NUMBER   VARCHAR2(200 BYTE),
   BRAND_NAME                  VARCHAR2(200 BYTE),
   DESCRIPTOR                  VARCHAR2(200 BYTE),
   PEDIATRIC_FLAG              VARCHAR2(1 BYTE),
   ACCESSION_NUMBER            VARCHAR2(5 BYTE),
   NUMBER_OF_AIS               VARCHAR2(10 BYTE),
   LAST_UPDATE_DATE            DATE,
   AI_GROUP_NO                 VARCHAR2(10 BYTE)
);

CREATE TABLE ACTIVE_INGREDIENTS_IA
(
   DRUG_CODE                NUMBER                NOT NULL,
   ACTIVE_INGREDIENT_CODE   NUMBER,
   INGREDIENT               VARCHAR2(240 BYTE),
   INGREDIENT_SUPPLIED_IND  VARCHAR2(1 BYTE),
   STRENGTH                 VARCHAR2(20 BYTE),
   STRENGTH_UNIT            VARCHAR2(40 BYTE),
   STRENGTH_TYPE            VARCHAR2(40 BYTE),
   DOSAGE_VALUE             VARCHAR2(20 BYTE),
   BASE                     VARCHAR2(1 BYTE),
   DOSAGE_UNIT              VARCHAR2(40 BYTE),
   NOTES                    VARCHAR2(2000 BYTE)
);

CREATE TABLE ACTIVE_INGREDIENTS_ACT
(
   DRUG_CODE                NUMBER                NOT NULL,
   ACTIVE_INGREDIENT_CODE   NUMBER,
   INGREDIENT               VARCHAR2(240 BYTE),
   INGREDIENT_SUPPLIED_IND  VARCHAR2(1 BYTE),
   STRENGTH                 VARCHAR2(20 BYTE),
   STRENGTH_UNIT            VARCHAR2(40 BYTE),
   STRENGTH_TYPE            VARCHAR2(40 BYTE),
   DOSAGE_VALUE             VARCHAR2(20 BYTE),
   BASE                     VARCHAR2(1 BYTE),
   DOSAGE_UNIT              VARCHAR2(40 BYTE),
   NOTES                    VARCHAR2(2000 BYTE)
);

CREATE TABLE FORM_ACT
(
   DRUG_CODE            NUMBER              NOT NULL,
   PHARM_FORM_CODE      NUMBER,
   PHARMACEUTICAL_FORM  VARCHAR2(45 BYTE)
);

CREATE TABLE FORM_IA
(
   DRUG_CODE            NUMBER              NOT NULL,
   PHARM_FORM_CODE      NUMBER,
   PHARMACEUTICAL_FORM  VARCHAR2(100 BYTE)
);

CREATE TABLE ROUTE_ACT
(
   DRUG_CODE                     VARCHAR2(15 BYTE),
   ROUTE_OF_ADMINISTRATION_CODE  NUMBER(6),
   ROUTE_OF_ADMINISTRATION       VARCHAR2(50 BYTE)
);

CREATE TABLE ROUTE_IA
(
   DRUG_CODE                     VARCHAR2(15 BYTE),
   ROUTE_OF_ADMINISTRATION_CODE  NUMBER(6),
   ROUTE_OF_ADMINISTRATION       VARCHAR2(50 BYTE)
);

CREATE TABLE PACKAGING_ACT
(
   DRUG_CODE            NUMBER(8)           NOT NULL,
   UPC                  VARCHAR2(12 BYTE),
   PACKAGE_SIZE_UNIT    VARCHAR2(40 BYTE),
   PACKAGE_TYPE         VARCHAR2(40 BYTE),
   PACKAGE_SIZE         VARCHAR2(5 BYTE),
   PRODUCT_INFORMATION  VARCHAR2(80 BYTE)
);

CREATE TABLE PACKAGING_IA
(
   DRUG_CODE            NUMBER(8)           NOT NULL,
   UPC                  VARCHAR2(12 BYTE),
   PACKAGE_SIZE_UNIT    VARCHAR2(80 BYTE),
   PACKAGE_TYPE         VARCHAR2(80 BYTE),
   PACKAGE_SIZE         VARCHAR2(85 BYTE),
   PRODUCT_INFORMATION  VARCHAR2(100 BYTE)
);

CREATE TABLE STATUS_ACT
(
   DRUG_CODE             VARCHAR2(255 BYTE),
   CURRENT_STATUS_FLAG  VARCHAR2(255 BYTE),
   STATUS               VARCHAR2(255 BYTE),
   HISTORY_DATE         DATE
);

CREATE TABLE STATUS_IA
(
   DRUG_CODE             VARCHAR2(255 BYTE),
   CURRENT_STATUS_FLAG  VARCHAR2(255 BYTE),
   STATUS               VARCHAR2(255 BYTE),
   HISTORY_DATE         DATE
);

CREATE TABLE COMPANIES_IA
(
   DRUG_CODE                  NUMBER(8)           NOT NULL,
   MFR_CODE                   VARCHAR2(15 BYTE),
   COMPANY_CODE               NUMBER(6),
   COMPANY_NAME               VARCHAR2(80 BYTE),
   COMPANY_TYPE               VARCHAR2(40 BYTE),
   ADDRESS_MAILING_FLAG       VARCHAR2(1 BYTE),
   ADDRESS_BILLING_FLAG       VARCHAR2(1 BYTE),
   ADDRESS_NOTIFICATION_FLAG  VARCHAR2(1 BYTE),
   ADDRESS_OTHER              VARCHAR2(1 BYTE),
   SUITE_NUMBER               VARCHAR2(50 BYTE),
   STREET_NAME                VARCHAR2(80 BYTE),
   CITY_NAME                  VARCHAR2(60 BYTE),
   PROVINCE                   VARCHAR2(40 BYTE),
   COUNTRY                    VARCHAR2(40 BYTE),
   POSTAL_CODE                VARCHAR2(20 BYTE),
   POST_OFFICE_BOX            VARCHAR2(25 BYTE)
);

CREATE TABLE COMPANIES_ACT
(
   DRUG_CODE                  NUMBER(8)           NOT NULL,
   MFR_CODE                   VARCHAR2(5 BYTE),
   COMPANY_CODE               NUMBER(6),
   COMPANY_NAME               VARCHAR2(80 BYTE),
   COMPANY_TYPE               VARCHAR2(40 BYTE),
   ADDRESS_MAILING_FLAG       VARCHAR2(1 BYTE),
   ADDRESS_BILLING_FLAG       VARCHAR2(1 BYTE),
   ADDRESS_NOTIFICATION_FLAG  VARCHAR2(1 BYTE),
   ADDRESS_OTHER              VARCHAR2(1 BYTE),
   SUITE_NUMBER               VARCHAR2(20 BYTE),
   STREET_NAME                VARCHAR2(80 BYTE),
   CITY_NAME                  VARCHAR2(60 BYTE),
   PROVINCE                   VARCHAR2(40 BYTE),
   COUNTRY                    VARCHAR2(40 BYTE),
   POSTAL_CODE                VARCHAR2(20 BYTE),
   POST_OFFICE_BOX            VARCHAR2(15 BYTE)
);

CREATE TABLE THERAPEUTIC_CLASS_IA
(
   DRUG_CODE       NUMBER(8)            NOT NULL,
   TC_ATC_NUMBER   VARCHAR2(8 BYTE),
   TC_ATC          VARCHAR2(120 BYTE),
   TC_AHFS_NUMBER  VARCHAR2(20 BYTE),
   TC_AHFS         VARCHAR2(80 BYTE)
);

CREATE TABLE THERAPEUTIC_CLASS_ACT
(
   DRUG_CODE       NUMBER(8)            NOT NULL,
   TC_ATC_NUMBER   VARCHAR2(8 BYTE),
   TC_ATC          VARCHAR2(120 BYTE),
   TC_AHFS_NUMBER  VARCHAR2(20 BYTE),
   TC_AHFS         VARCHAR2(80 BYTE)
);

CREATE TABLE DRUG_AP
(
   DRUG_CODE                   NUMBER               NOT NULL,
   PRODUCT_CATEGORIZATION      VARCHAR2(80 BYTE),
   CLASS                       VARCHAR2(40 BYTE),
   DRUG_IDENTIFICATION_NUMBER   VARCHAR2(200 BYTE),
   BRAND_NAME                  VARCHAR2(200 BYTE),
   DESCRIPTOR                  VARCHAR2(200 BYTE),
   PEDIATRIC_FLAG              VARCHAR2(1 BYTE),
   ACCESSION_NUMBER            VARCHAR2(5 BYTE),
   NUMBER_OF_AIS               VARCHAR2(10 BYTE),
   LAST_UPDATE_DATE            DATE,
   AI_GROUP_NO                 VARCHAR2(10 BYTE)
);

CREATE TABLE ACTIVE_INGREDIENTS_AP
(
   DRUG_CODE                NUMBER                NOT NULL,
   ACTIVE_INGREDIENT_CODE   NUMBER,
   INGREDIENT               VARCHAR2(240 BYTE),
   INGREDIENT_SUPPLIED_IND  VARCHAR2(1 BYTE),
   STRENGTH                 VARCHAR2(20 BYTE),
   STRENGTH_UNIT            VARCHAR2(40 BYTE),
   STRENGTH_TYPE            VARCHAR2(40 BYTE),
   DOSAGE_VALUE             VARCHAR2(20 BYTE),
   BASE                     VARCHAR2(1 BYTE),
   DOSAGE_UNIT              VARCHAR2(40 BYTE),
   NOTES                    VARCHAR2(2000 BYTE)
);

CREATE TABLE FORM_AP
(
   DRUG_CODE            NUMBER              NOT NULL,
   PHARM_FORM_CODE      NUMBER,
   PHARMACEUTICAL_FORM  VARCHAR2(45 BYTE)
);

CREATE TABLE ROUTE_AP
(
   DRUG_CODE                     VARCHAR2(15 BYTE),
   ROUTE_OF_ADMINISTRATION_CODE  NUMBER(6),
   ROUTE_OF_ADMINISTRATION       VARCHAR2(50 BYTE)
);

CREATE TABLE PACKAGING_AP
(
   DRUG_CODE            NUMBER(8)           NOT NULL,
   UPC                  VARCHAR2(12 BYTE),
   PACKAGE_SIZE_UNIT    VARCHAR2(40 BYTE),
   PACKAGE_TYPE         VARCHAR2(40 BYTE),
   PACKAGE_SIZE         VARCHAR2(5 BYTE),
   PRODUCT_INFORMATION  VARCHAR2(80 BYTE)
);

CREATE TABLE STATUS_AP
(
   DRUG_CODE             VARCHAR2(255 BYTE),
   CURRENT_STATUS_FLAG  VARCHAR2(255 BYTE),
   STATUS               VARCHAR2(255 BYTE),
   HISTORY_DATE         DATE
);

CREATE TABLE COMPANIES_AP
(
   DRUG_CODE                  NUMBER(8)           NOT NULL,
   MFR_CODE                   VARCHAR2(5 BYTE),
   COMPANY_CODE               NUMBER(6),
   COMPANY_NAME               VARCHAR2(80 BYTE),
   COMPANY_TYPE               VARCHAR2(40 BYTE),
   ADDRESS_MAILING_FLAG       VARCHAR2(1 BYTE),
   ADDRESS_BILLING_FLAG       VARCHAR2(1 BYTE),
   ADDRESS_NOTIFICATION_FLAG  VARCHAR2(1 BYTE),
   ADDRESS_OTHER              VARCHAR2(1 BYTE),
   SUITE_NUMBER               VARCHAR2(20 BYTE),
   STREET_NAME                VARCHAR2(80 BYTE),
   CITY_NAME                  VARCHAR2(60 BYTE),
   PROVINCE                   VARCHAR2(40 BYTE),
   COUNTRY                    VARCHAR2(40 BYTE),
   POSTAL_CODE                VARCHAR2(20 BYTE),
   POST_OFFICE_BOX            VARCHAR2(15 BYTE)
);

CREATE TABLE THERAPEUTIC_CLASS_AP
(
   DRUG_CODE       NUMBER(8)            NOT NULL,
   TC_ATC_NUMBER   VARCHAR2(8 BYTE),
   TC_ATC          VARCHAR2(120 BYTE),
   TC_AHFS_NUMBER  VARCHAR2(20 BYTE),
   TC_AHFS         VARCHAR2(80 BYTE)
);
         
—-CREATE MANUAL TABLES
CREATE TABLE NEW_PACK
(
   CONCEPT_CODE       VARCHAR2(30 BYTE),
   AIC                VARCHAR2(240 BYTE),
   CONCEPT_NAME       VARCHAR2(240 BYTE),
   INGREDIENT         VARCHAR2(240 BYTE),
   AMOUNT_VALUE       VARCHAR2(20 BYTE),
   AMOUNT_UNIT        VARCHAR2(40 BYTE),
   DENOMINATOR_VALUE  VARCHAR2(40 BYTE),
   DENOMINATOR_UNIT   VARCHAR2(40 BYTE),
   NUMERATOR_VALUE    VARCHAR2(20 BYTE),
   NUMERATOR_UNIT     VARCHAR2(40 BYTE),
   NOTES              VARCHAR2(2000 BYTE),
   DRUG_CODE          VARCHAR2(10 BYTE),
   BRAND_NAME         VARCHAR2(200 BYTE),
   NUMBER_OF_AIS      VARCHAR2(10 BYTE),
   INVALID_REASON     VARCHAR2(255 BYTE)
);

CREATE TABLE PACK_FORM
(
   CONCEPT_NAME_1       VARCHAR(255),
   CONCEPT_NAME_2       VARCHAR(255)
);   

CREATE TABLE PC_STAGE_MANUAL
(
   CONCEPT_NAME_1       VARCHAR(255),
   CONCEPT_NAME_2       VARCHAR(1255),
   AMOUNT               VARCHAR(255),
   BOX_SIZE             VARCHAR(255)
);  

