DROP TABLE DRUG_CONCEPT_STAGE;
DROP TABLE DS_STAGE;
DROP TABLE INTERNAL_RELATIONSHIP_STAGE;
DROP TABLE RELATIONSHIP_TO_CONCEPT;
DROP TABLE PC_STAGE;
DROP TABLE CONCEPT_SYNONYM_STAGE;



DROP TABLE NON_DRUG;
DROP TABLE NEW_PACK;
DROP TABLE PACK_FORM;
DROP TABLE PREV_RTC;
DROP TABLE PC_STAGE_MANUAL;
DROP TABLE DRUG_PRODUCT;
DROP TABLE ACTIVE_INGREDIENTS;
DROP TABLE ROUTE;
DROP TABLE FORM;
DROP TABLE STATUS;
DROP TABLE PACKAGING;
DROP TABLE COMPANIES;
DROP TABLE THERAPEUTIC_CLASS;
DROP TABLE UNIT;
DROP TABLE MANUFACTURER
DROP TABLE INGR ;
DROP TABLE INGR_OMOP;
DROP TABLE INGR_2;
DROP TABLE FORMS;
DROP TABLE FORMS_2;
DROP TABLE BRAND_NAME;
DROP SEQUENCE CONC_STAGE_SEQ ;
DROP TABLE LIST_TEMP;
DROP TABLE DATES;
DROP TABLE DS_STAGE_0;
DROP TABLE DS_STAGE_1;
DROP TABLE NEW_RTC ;


DROP TABLE DRUG_IA;
DROP TABLE DRUG_ACT;
DROP TABLE DRUG_AP;
DROP TABLE ROUTE_IA;
DROP TABLE ROUTE_ACT;
DROP TABLE ROUTE_AP;
DROP TABLE ACTIVE_INGREDIENTS_IA;
DROP TABLE ACTIVE_INGREDIENTS_ACT;
DROP TABLE ACTIVE_INGREDIENTS_AP;
DROP TABLE FORM_IA;
DROP TABLE FORM_ACT;
DROP TABLE FORM_AP;
DROP TABLE PACKAGING_ACT;
DROP TABLE PACKAGING_IA;
DROP TABLE PACKAGING_AP;
DROP TABLE STATUS_ACT;
DROP TABLE STATUS_IA;
DROP TABLE STATUS_AP;
DROP TABLE COMPANIES_ACT;
DROP TABLE COMPANIES_IA;
DROP TABLE COMPANIES_AP;
DROP TABLE THERAPEUTIC_CLASS_IA;
DROP TABLE THERAPEUTIC_CLASS_ACT;
DROP TABLE THERAPEUTIC_CLASS_AP;