
--Brand Names--
drop table relation_brandname_1;
create table relation_brandname_1 as
select d.concept_name, concept_id, r.concept_name as R from drug_concept_stage d
inner join devv5.concept r on trim(lower(d.concept_name)) = trim(lower(r.concept_name))  WHERE  d.concept_class_id like '%Brand%' and r.VOCABULARY_ID like '%Rx%' 
and r.INVALID_REASON is null AND r.concept_class_id like '%Brand Name%'
;
insert into relation_brandname_1
select CONCEPT_NAME,CONCEPT_ID_2,CONCEPT_NAME_2 from RELATION_MANUAL_BN;

--ingredients--
drop table RELATION_INGR_1;
create table RELATION_INGR_1 as
select d.concept_name, concept_id, r.concept_name as R from drug_concept_stage d
inner join devv5.concept r on trim(lower(d.concept_name)) = trim(lower(r.concept_name)) 
where  d.concept_class_id like '%Ingredient%' and r.VOCABULARY_ID like '%Rx%' and r.INVALID_REASON is null
and r.concept_class_id like 'Ingredient%'
; 


insert into RELATION_INGR_1
select d.concept_name, concept_id, CONCEPT_SYNONYM_NAME as R from drug_concept_stage d
inner join devv5.CONCEPT_SYNONYM r on trim(lower(d.concept_name)) = trim(lower(CONCEPT_SYNONYM_NAME)) 
where  d.concept_class_id like '%Ingredient%' and concept_id in  (select concept_id from devv5.concept where VOCABULARY_ID like '%Rx%' and INVALID_REASON is null
and concept_class_id like 'Ingredient%') and concept_code not in (select concept_code from RELATION_INGR_1)
;
insert into RELATION_INGR_1
select CONCEPT_NAME,CONCEPT_ID_2,CONCEPT_NAME_2 from RELATION_MANUAL_INGR;
 alter table RELATION_INGR_1
 add PRECEDENCE number;
 
 DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'AESCULUS HIPPOCASTANUM' AND   CONCEPT_ID = 44818465 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'APRICOT' AND   CONCEPT_ID = 40170375 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'APRICOT' AND   CONCEPT_ID = 42904131 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'APRICOT' AND   CONCEPT_ID = 42900392 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'APRICOT' AND   CONCEPT_ID = 42900393 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'BUTYLENE GLYCOL' AND   CONCEPT_ID = 35605008 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'BUTYLENE GLYCOL' AND   CONCEPT_ID = 46221190 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'BUTYLENE GLYCOL' AND   CONCEPT_ID = 43533041 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'BUTYLENE GLYCOL' AND   CONCEPT_ID = 43532985 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'HOPS' AND   CONCEPT_ID = 35603443 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'SUNFLOWER' AND   CONCEPT_ID = 40172580 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'SUNFLOWER' AND   CONCEPT_ID = 40162079 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'SUNFLOWER' AND   CONCEPT_ID = 42900564 AND   PRECEDENCE IS NULL;
DELETE FROM RELATION_INGR_1 WHERE CONCEPT_NAME = 'THYME' AND   CONCEPT_ID = 43013853 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 44784661 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 40160955 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 40170299 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 35606015 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 46221189 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 42628986 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 43012212 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 44785547 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 9 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 46233723 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 10 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 45775957 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 11 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 40169251 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 12 WHERE CONCEPT_NAME = 'ACACIA' AND   CONCEPT_ID = 43013270 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'AESCULUS HIPPOCASTANUM' AND   CONCEPT_ID = 42898420 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'AESCULUS HIPPOCASTANUM' AND   CONCEPT_ID = 42898419 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'AESCULUS HIPPOCASTANUM' AND   CONCEPT_ID = 42898418 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ALISMA' AND   CONCEPT_ID = 45776741 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ALISMA' AND   CONCEPT_ID = 43532995 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ALISMA' AND   CONCEPT_ID = 43525880 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 9 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 45892130 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 42903463 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 1315376 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 35605242 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 42900341 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 42900340 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 958994 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 42898390 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 960900 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 10 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 43526564 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 11 WHERE CONCEPT_NAME = 'ALOES' AND   CONCEPT_ID = 43525966 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ALPINA GALANGA' AND   CONCEPT_ID = 42899009 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ALPINA GALANGA' AND   CONCEPT_ID = 35606084 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ALPINA GALANGA' AND   CONCEPT_ID = 42898393 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ALTHAEA OFFICINALIS' AND   CONCEPT_ID = 43533001 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ALTHAEA OFFICINALIS' AND   CONCEPT_ID = 42898411 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ALTHAEA OFFICINALIS' AND   CONCEPT_ID = 42898264 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'ALTHAEA OFFICINALIS' AND   CONCEPT_ID = 43560012 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 23 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 43125909 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 22 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 43013356 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 21 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898332 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 20 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 1319232 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 19 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898279 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 18 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 46221714 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 17 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898278 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 16 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 44814302 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 15 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898331 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 14 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 46234378 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 13 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898330 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 12 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 45776245 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 11 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898329 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 10 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 44814270 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 9 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 45775258 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898328 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 46221691 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 43012497 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 43560461 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898327 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898326 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 43525819 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ANGELICA' AND   CONCEPT_ID = 42898325 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'APRICOT' AND   CONCEPT_ID = 42903960 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'APRICOT' AND   CONCEPT_ID = 43533033 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ARCTIUM' AND   CONCEPT_ID = 42903466 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ARCTIUM' AND   CONCEPT_ID = 45776103 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ARCTIUM' AND   CONCEPT_ID = 42898350 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ARCTOSTAPHYLOS UVA-URSI' AND   CONCEPT_ID = 46275331 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ARCTOSTAPHYLOS UVA-URSI' AND   CONCEPT_ID = 42900397 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ARNICA MONTANA' AND   CONCEPT_ID = 42898360 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ARNICA MONTANA' AND   CONCEPT_ID = 44785117 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ARNICA MONTANA' AND   CONCEPT_ID = 19071833 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ASPARAGUS' AND   CONCEPT_ID = 43125996 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'ASPARAGUS' AND   CONCEPT_ID = 42900400 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ASPARAGUS' AND   CONCEPT_ID = 44784670 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'AVENA SATIVA' AND   CONCEPT_ID = 42903740 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'AVENA SATIVA' AND   CONCEPT_ID = 42898638 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'AVENA SATIVA' AND   CONCEPT_ID = 42898637 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'BACILLUS CALMETTE-GUERIN' AND   CONCEPT_ID = 19015423 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'BACILLUS CALMETTE-GUERIN' AND   CONCEPT_ID = 19086176 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'BACILLUS CALMETTE-GUERIN' AND   CONCEPT_ID = 19013730 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'BACILLUS CALMETTE-GUERIN' AND   CONCEPT_ID = 19023835 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'BAPTISIA' AND   CONCEPT_ID = 42898622 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'BAPTISIA' AND   CONCEPT_ID = 42904304 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'BIFIDOBACTERIUM' AND   CONCEPT_ID = 40242573 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'BIFIDOBACTERIUM' AND   CONCEPT_ID = 40242566 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'BIFIDOBACTERIUM' AND   CONCEPT_ID = 19136097 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'BIFIDOBACTERIUM' AND   CONCEPT_ID = 19006764 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'BIFIDOBACTERIUM' AND   CONCEPT_ID = 45776867 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'BILBERRY' AND   CONCEPT_ID = 44784998 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'BILBERRY' AND   CONCEPT_ID = 43525782 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'BILBERRY' AND   CONCEPT_ID = 1314955 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'BRYONIA' AND   CONCEPT_ID = 19015636 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'BRYONIA' AND   CONCEPT_ID = 42904031 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'BRYONIA' AND   CONCEPT_ID = 42904146 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'BRYONIA' AND   CONCEPT_ID = 42898489 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'BUPLEURUM' AND   CONCEPT_ID = 42898494 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'BUPLEURUM' AND   CONCEPT_ID = 42898493 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CALENDULA' AND   CONCEPT_ID = 43532988 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'CALENDULA' AND   CONCEPT_ID = 42898557 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'CALENDULA' AND   CONCEPT_ID = 42898771 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'CALENDULA' AND   CONCEPT_ID = 42898770 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CALENDULA' AND   CONCEPT_ID = 19071836 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'CALENDULA' AND   CONCEPT_ID = 35604983 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CAMELLIA SINENSIS' AND   CONCEPT_ID = 42904180 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'CAMELLIA SINENSIS' AND   CONCEPT_ID = 43012418 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CAMELLIA SINENSIS' AND   CONCEPT_ID = 35606317 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'CAMELLIA SINENSIS' AND   CONCEPT_ID = 42898782 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'CAMELLIA SINENSIS' AND   CONCEPT_ID = 42898781 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'CAPSICUM' AND   CONCEPT_ID = 19055492 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CAPSICUM' AND   CONCEPT_ID = 915553 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CAPSICUM' AND   CONCEPT_ID = 42903902 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CENTELLA ASIATICA' AND   CONCEPT_ID = 42898717 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CENTELLA ASIATICA' AND   CONCEPT_ID = 42898716 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CHAMOMILE' AND   CONCEPT_ID = 19052620 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CHAMOMILE' AND   CONCEPT_ID = 42898758 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'CHELIDONIUM' AND   CONCEPT_ID = 43013541 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CHELIDONIUM' AND   CONCEPT_ID = 43560075 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CHELIDONIUM' AND   CONCEPT_ID = 19071835 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CHONDROITIN' AND   CONCEPT_ID = 1395573 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CHONDROITIN' AND   CONCEPT_ID = 42903714 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET CONCEPT_ID = 45776108,
       PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CIMICIFUGA' AND   CONCEPT_ID = 45776108 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET CONCEPT_ID = 42898407,
       PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CIMICIFUGA' AND   CONCEPT_ID = 42898407 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'COMFREY' AND   CONCEPT_ID = 42904063 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'COMFREY' AND   CONCEPT_ID = 42903951 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'CORDYCEPS' AND   CONCEPT_ID = 43532068 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'CORDYCEPS' AND   CONCEPT_ID = 19070923 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'CORDYCEPS' AND   CONCEPT_ID = 45892323 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'COWSLIP' AND   CONCEPT_ID = 44785730 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'COWSLIP' AND   CONCEPT_ID = 42899873 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'DIOSCOREA' AND   CONCEPT_ID = 42899038 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'DIOSCOREA' AND   CONCEPT_ID = 46221697 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'DIOSCOREA' AND   CONCEPT_ID = 42899037 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'DIOSCOREA' AND   CONCEPT_ID = 42899036 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'DONG QUAI' AND   CONCEPT_ID = 43013356 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'DONG QUAI' AND   CONCEPT_ID = 42898332 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'DONG QUAI' AND   CONCEPT_ID = 1319232 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 1359148 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 1398816 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 42899040 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 1399063 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 19059159 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 1389112 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 40175995 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 43012668 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 9 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 1398677 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 10 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 42899031 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 11 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 1391199 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 12 WHERE CONCEPT_NAME = 'ECHINACEA' AND   CONCEPT_ID = 1304233 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'EPOETIN' AND   CONCEPT_ID = 21014076 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'EPOETIN' AND   CONCEPT_ID = 21014072 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'EPOETIN' AND   CONCEPT_ID = 21014058 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'EPOETIN' AND   CONCEPT_ID = 19001311 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'EPOETIN' AND   CONCEPT_ID = 1301125 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'EQUISETUM ARVENSE' AND   CONCEPT_ID = 44818471 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'EQUISETUM ARVENSE' AND   CONCEPT_ID = 42899033 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'EQUISETUM ARVENSE' AND   CONCEPT_ID = 42899032 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'EUPHORBIA' AND   CONCEPT_ID = 43525792 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'EUPHORBIA' AND   CONCEPT_ID = 42898972 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'EUPHORBIA' AND   CONCEPT_ID = 35605011 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'EUPHORBIA' AND   CONCEPT_ID = 42904037 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'EUPHORBIA' AND   CONCEPT_ID = 45776415 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'EUPHORBIA' AND   CONCEPT_ID = 42904088 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'EUPHORBIA' AND   CONCEPT_ID = 45776145 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'EUPHRASIA' AND   CONCEPT_ID = 42904127 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 9 WHERE CONCEPT_NAME = 'EUPHRASIA' AND   CONCEPT_ID = 1304412 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'FENUGREEK' AND   CONCEPT_ID = 19037415 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'FENUGREEK' AND   CONCEPT_ID = 19004145 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'FENUGREEK' AND   CONCEPT_ID = 42900516 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'FRANGULA' AND   CONCEPT_ID = 43125917 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'FRANGULA' AND   CONCEPT_ID = 42904096 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'FRANGULA' AND   CONCEPT_ID = 19016537 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'FRANGULA' AND   CONCEPT_ID = 42898997 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'FRANGULA' AND   CONCEPT_ID = 42898996 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'GYMNEMA SYLVESTRE' AND   CONCEPT_ID = 19070953 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'GYMNEMA SYLVESTRE' AND   CONCEPT_ID = 44816309 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'HAMAMELIS' AND   CONCEPT_ID = 42903910 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'HAMAMELIS' AND   CONCEPT_ID = 42899159 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'HAMAMELIS' AND   CONCEPT_ID = 42899158 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'HAMAMELIS' AND   CONCEPT_ID = 42899157 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'HAMAMELIS' AND   CONCEPT_ID = 42899156 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'HAMAMELIS' AND   CONCEPT_ID = 42899155 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'HAMAMELIS' AND   CONCEPT_ID = 42899154 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'HAMAMELIS' AND   CONCEPT_ID = 42899153 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'HEPATITIS A VACCINE' AND   CONCEPT_ID = 44814322 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'HEPATITIS A VACCINE' AND   CONCEPT_ID = 596876 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'HOPS' AND   CONCEPT_ID = 21014134 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'HOPS' AND   CONCEPT_ID = 1398499 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'HYALURONIC ACID' AND   CONCEPT_ID = 787787 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'HYALURONIC ACID' AND   CONCEPT_ID = 798336 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'HYDRASTIS' AND   CONCEPT_ID = 19013826 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'HYDRASTIS' AND   CONCEPT_ID = 42903884 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'HYPERICUM PERFORATUM' AND   CONCEPT_ID = 42899140 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'HYPERICUM PERFORATUM' AND   CONCEPT_ID = 42899138 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'INSULIN ZINC' AND   CONCEPT_ID = 1562586 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'INSULIN ZINC' AND   CONCEPT_ID = 1513849 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'IVY' AND   CONCEPT_ID = 19091179 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'IVY' AND   CONCEPT_ID = 43125950 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'LINOLEIC ACID' AND   CONCEPT_ID = 19070929 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'LINOLEIC ACID' AND   CONCEPT_ID = 19100751 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'LYCOPERSICON' AND   CONCEPT_ID = 46234076 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'LYCOPERSICON' AND   CONCEPT_ID = 43013842 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'MAGNOLIA OFFICINALIS' AND   CONCEPT_ID = 42899334 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'MAGNOLIA OFFICINALIS' AND   CONCEPT_ID = 42899333 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'MAIZE STARCH' AND   CONCEPT_ID = 43532428 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'MAIZE STARCH' AND   CONCEPT_ID = 43532010 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'MAIZE STARCH' AND   CONCEPT_ID = 43012351 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'MELALEUCA' AND   CONCEPT_ID = 43526876 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'MELALEUCA' AND   CONCEPT_ID = 44785700 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'MELALEUCA' AND   CONCEPT_ID = 42899420 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'MELALEUCA' AND   CONCEPT_ID = 43560198 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'MELISSA OFFICINALIS' AND   CONCEPT_ID = 42899427 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'MELISSA OFFICINALIS' AND   CONCEPT_ID = 42899426 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'MELISSA OFFICINALIS' AND   CONCEPT_ID = 42899425 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'MENTHA PIPERITA' AND   CONCEPT_ID = 42899303 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'MENTHA PIPERITA' AND   CONCEPT_ID = 42904027 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'METHOHEXITONE' AND   CONCEPT_ID = 21014071 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'METHOHEXITONE' AND   CONCEPT_ID = 19005015 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'OLEA EUROPAEA' AND   CONCEPT_ID = 43526293 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'OLEA EUROPAEA' AND   CONCEPT_ID = 42899542 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'OLEA EUROPAEA' AND   CONCEPT_ID = 42899640 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'OLEA EUROPAEA' AND   CONCEPT_ID = 42904017 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'OLEA EUROPAEA' AND   CONCEPT_ID = 43526292 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'OLEA EUROPAEA' AND   CONCEPT_ID = 35606159 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 9 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 43526289 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 42899590 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 42899589 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 35604868 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 44814385 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 42899588 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 44814384 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 42899587 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'PAEONIA' AND   CONCEPT_ID = 45776221 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'PANAX GINSENG' AND   CONCEPT_ID = 43013750 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'PANAX GINSENG' AND   CONCEPT_ID = 42899598 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'PANAX GINSENG' AND   CONCEPT_ID = 42899597 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'PANAX GINSENG' AND   CONCEPT_ID = 42899596 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'PASSIFLORA INCARNATA' AND   CONCEPT_ID = 35606039 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'PASSIFLORA INCARNATA' AND   CONCEPT_ID = 42899545 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'PASSIFLORA INCARNATA' AND   CONCEPT_ID = 43525821 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'PASSIFLORA INCARNATA' AND   CONCEPT_ID = 35603949 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'PASSIFLORA INCARNATA' AND   CONCEPT_ID = 42899632 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'PASSIFLORA INCARNATA' AND   CONCEPT_ID = 42904145 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'PASSIFLORA INCARNATA' AND   CONCEPT_ID = 19065820 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'PERILLA FRUTESCENS' AND   CONCEPT_ID = 42899557 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'PERILLA FRUTESCENS' AND   CONCEPT_ID = 42899602 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'PERILLA FRUTESCENS' AND   CONCEPT_ID = 42899556 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'PERILLA FRUTESCENS' AND   CONCEPT_ID = 42899601 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'PERILLA FRUTESCENS' AND   CONCEPT_ID = 42899600 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'PLANTAGO MAJOR' AND   CONCEPT_ID = 42899920 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'PLANTAGO MAJOR' AND   CONCEPT_ID = 42899919 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'PLANTAGO MAJOR' AND   CONCEPT_ID = 42899918 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'POLIOMYELITIS VACCINE - INACTIVATED' AND   CONCEPT_ID = 523367 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'POLIOMYELITIS VACCINE - INACTIVATED' AND   CONCEPT_ID = 523365 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'POLIOMYELITIS VACCINE - INACTIVATED' AND   CONCEPT_ID = 523283 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'POLYGONUM CUSPIDATUM' AND   CONCEPT_ID = 43526319 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'POLYGONUM CUSPIDATUM' AND   CONCEPT_ID = 42899950 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'POLYGONUM CUSPIDATUM' AND   CONCEPT_ID = 44814593 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'POLYOXYL HYDROGENATED CASTOR OILS' AND   CONCEPT_ID = 42899578 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'POLYOXYL HYDROGENATED CASTOR OILS' AND   CONCEPT_ID = 43532079 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'POLYOXYL HYDROGENATED CASTOR OILS' AND   CONCEPT_ID = 42899576 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'POMEGRANATE' AND   CONCEPT_ID = 42899579 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'POMEGRANATE' AND   CONCEPT_ID = 42904274 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET R = 'Pomegranate Extract',
       PRECEDENCE = 1 WHERE CONCEPT_NAME = 'POMEGRANATE' AND   CONCEPT_ID = 1315003 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'POPULUS' AND   CONCEPT_ID = 42899867 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'POPULUS' AND   CONCEPT_ID = 42899866 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'POPULUS' AND   CONCEPT_ID = 45774934 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'POPULUS' AND   CONCEPT_ID = 42899865 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'POPULUS' AND   CONCEPT_ID = 43533010 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'PRUNUS SEROTINA' AND   CONCEPT_ID = 42899963 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'PRUNUS SEROTINA' AND   CONCEPT_ID = 42899962 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'QUASSIA' AND   CONCEPT_ID = 42899832 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'QUASSIA' AND   CONCEPT_ID = 43013798 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'RABIES VACCINE' AND   CONCEPT_ID = 544411 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'RABIES VACCINE' AND   CONCEPT_ID = 544505 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'REHMANNIA' AND   CONCEPT_ID = 44814419 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'REHMANNIA' AND   CONCEPT_ID = 42899772 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'RHUBARB' AND   CONCEPT_ID = 19060995 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'RHUBARB' AND   CONCEPT_ID = 44814229 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'RUMEX ACETOSA' AND   CONCEPT_ID = 35605326 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'RUMEX ACETOSA' AND   CONCEPT_ID = 43012310 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 44814431 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 42903421 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 45892775 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 9 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 36249385 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 42899714 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 42899713 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 44816296 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 42899734 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'SALIX' AND   CONCEPT_ID = 42899712 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'SALVIA OFFICINALIS' AND   CONCEPT_ID = 44507633 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'SALVIA OFFICINALIS' AND   CONCEPT_ID = 44785368 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'SAMBUCUS' AND   CONCEPT_ID = 43012403 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'SAMBUCUS' AND   CONCEPT_ID = 35603511 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'SAMBUCUS' AND   CONCEPT_ID = 42899721 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'SAMBUCUS' AND   CONCEPT_ID = 42899720 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'SAMBUCUS' AND   CONCEPT_ID = 42904069 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'SAMBUCUS' AND   CONCEPT_ID = 43526356 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'SARSAPARILLA' AND   CONCEPT_ID = 42899741 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'SARSAPARILLA' AND   CONCEPT_ID = 19056120 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'SCUTELLARIA' AND   CONCEPT_ID = 42899758 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'SCUTELLARIA' AND   CONCEPT_ID = 46233905 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'SCUTELLARIA' AND   CONCEPT_ID = 46275334 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'SCUTELLARIA' AND   CONCEPT_ID = 42899757 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'SCUTELLARIA' AND   CONCEPT_ID = 45775042 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'SENEGA' AND   CONCEPT_ID = 46234431 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'SENEGA' AND   CONCEPT_ID = 42899945 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'SENNA' AND   CONCEPT_ID = 19086491 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'SENNA' AND   CONCEPT_ID = 44507644 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'SENNA' AND   CONCEPT_ID = 45893009 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'SENNA' AND   CONCEPT_ID = 992409 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'SENNA' AND   CONCEPT_ID = 960820 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'SENNA' AND   CONCEPT_ID = 42899777 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'SENNA' AND   CONCEPT_ID = 43526359 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 8 WHERE CONCEPT_NAME = 'SENNA' AND   CONCEPT_ID = 42899776 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'SOLIDAGO' AND   CONCEPT_ID = 46275329 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'SOLIDAGO' AND   CONCEPT_ID = 42899753 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'SOLIDAGO' AND   CONCEPT_ID = 42900078 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'SOLIDAGO' AND   CONCEPT_ID = 42903632 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'SOLIDAGO' AND   CONCEPT_ID = 42900077 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = NULL WHERE CONCEPT_NAME = 'SUNFLOWER' AND   CONCEPT_ID = 19040871 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'TAGETES' AND   CONCEPT_ID = 43012993 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'TAGETES' AND   CONCEPT_ID = 45774892 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'TAGETES' AND   CONCEPT_ID = 42900218 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'TAMARIND' AND   CONCEPT_ID = 42900219 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'TAMARIND' AND   CONCEPT_ID = 46234396 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'TARAXACUM' AND   CONCEPT_ID = 42900228 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'TARAXACUM' AND   CONCEPT_ID = 42900227 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'TARAXACUM' AND   CONCEPT_ID = 42900225 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'TARAXACUM' AND   CONCEPT_ID = 46234392 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'TARAXACUM' AND   CONCEPT_ID = 45776231 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'THUJA' AND   CONCEPT_ID = 42900084 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'THUJA' AND   CONCEPT_ID = 42904249 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'THUJA' AND   CONCEPT_ID = 42900083 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'THUJA' AND   CONCEPT_ID = 19082629 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'THUJA' AND   CONCEPT_ID = 42900082 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'THUJA' AND   CONCEPT_ID = 42900081 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'THUJA' AND   CONCEPT_ID = 42900080 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'THYME' AND   CONCEPT_ID = 19060834 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'TRIFOLIUM PRATENSE' AND   CONCEPT_ID = 42904049 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'TRIFOLIUM PRATENSE' AND   CONCEPT_ID = 43013016 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'TRIFOLIUM PRATENSE' AND   CONCEPT_ID = 42900047 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'URTICA' AND   CONCEPT_ID = 42900056 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'URTICA' AND   CONCEPT_ID = 19071810 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'URTICA' AND   CONCEPT_ID = 43013863 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'URTICA' AND   CONCEPT_ID = 1315629 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 5 WHERE CONCEPT_NAME = 'URTICA' AND   CONCEPT_ID = 42900055 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 6 WHERE CONCEPT_NAME = 'URTICA' AND   CONCEPT_ID = 19097592 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 7 WHERE CONCEPT_NAME = 'URTICA' AND   CONCEPT_ID = 42900054 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'VALERIAN' AND   CONCEPT_ID = 44818506 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'VALERIAN' AND   CONCEPT_ID = 1397059 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 1 WHERE CONCEPT_NAME = 'VITIS VINIFERA' AND   CONCEPT_ID = 42900068 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 2 WHERE CONCEPT_NAME = 'VITIS VINIFERA' AND   CONCEPT_ID = 35606157 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 3 WHERE CONCEPT_NAME = 'VITIS VINIFERA' AND   CONCEPT_ID = 43525901 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE = 4 WHERE CONCEPT_NAME = 'VITIS VINIFERA' AND   CONCEPT_ID = 42900062 AND   PRECEDENCE IS NULL;
UPDATE RELATION_INGR_1    SET PRECEDENCE  = 1 WHERE PRECEDENCE is null;
update  RELATION_INGR_1
set concept_name= regexp_substr(concept_name, '[^"].*[^"]');
update  RELATION_INGR_1
set r =regexp_substr(r, '[^"].*[^"]');


--relationship to suplliers--
drop table relation_supp_manual;
create table relation_supp_manual
(CONCEPT_CODE_1	VARCHAR(255),
concept_name_1	VARCHAR(255),
concept_ID_2	NUMBER,
CONCEPT_NAME_2 VARCHAR(255),
PRECEDENCE NUMBER);
WbImport -file=C:/Users/eallakhverdiiev/Desktop/relation_manual_supp.txt
         -type=text
         -table=RELATION_SUPP_MANUAL
         -encoding="ISO-8859-15"
         -header=true
         -decode=false
         -dateFormat="yyyy-MM-dd"
         -timestampFormat="yyyy-MM-dd HH:mm:ss"
         -delimiter='\t'
         -decimal=.
         -fileColumns=CONCEPT_NAME_1,CONCEPT_ID_2,CONCEPT_NAME_2
         -quoteCharEscaping=none
         -ignoreIdentityColumns=false
         -deleteTarget=true
         -continueOnError=false
         -batchSize=100;
         update  relation_supp_manual
set concept_name_1 =regexp_substr(concept_name_1, '[^"].*[^"]');
         update  relation_supp_manual
set concept_name_2 =regexp_substr(concept_name_2, '[^"].*[^"]');
         update  relation_supp_manual
set concept_ID_2 =regexp_substr(concept_ID_2, '[^"].*[^"]');


--Dose FORM--
drop table aus_dose_forms_done;
create table aus_dose_forms_done
(dose_form varchar(255),
concept_id NUMBER,
concept_name varchar(255),
precedence NUMBER);
WbImport -file=C:/Users/eallakhverdiiev/Desktop/aus_local_forms_done.txt
         -type=text
         -table=AUS_DOSE_FORMS_DONE
         -encoding="ISO-8859-15"
         -header=true
         -decode=false
         -dateFormat="yyyy-MM-dd"
         -timestampFormat="yyyy-MM-dd HH:mm:ss"
         -delimiter='\t'
         -decimal=.
         -fileColumns=DOSE_FORM,CONCEPT_ID,CONCEPT_NAME,PRECEDENCE
         -quoteCharEscaping=none
         -ignoreIdentityColumns=false
         -deleteTarget=true
         -continueOnError=false
         -batchSize=100;
--relationship to unit--
drop table relation_to_concept_unit;
create table relation_to_concept_unit
(
concept_code varchar(255),
concept_name varchar(255), 
concept_id_2 float(126),
concept_name_2 varchar(255),
precedence number,
converstion_factor float(126)
);
WbImport -file=C:/Users/eallakhverdiiev/Desktop/UNitts.txt
         -type=text
         -table=RELATION_TO_CONCEPT_UNIT
         -encoding="ISO-8859-15"
         -header=true
         -decode=false
         -dateFormat="yyyy-MM-dd"
         -timestampFormat="yyyy-MM-dd HH:mm:ss"
         -delimiter='\t'
         -decimal=.
         -fileColumns=CONCEPT_CODE,CONCEPT_NAME,CONCEPT_ID_2,CONCEPT_NAME_2,PRECEDENCE,CONVERSTION_FACTOR
         -quoteCharEscaping=none
         -ignoreIdentityColumns=false
         -deleteTarget=true
         -continueOnError=false
         -batchSize=100;
UPDATE relation_to_concept_unit SET CONVERSTION_FACTOR=1 WHERE CONVERSTION_FACTOR IS NULL;
UPDATE aus_dose_forms_done SET DOSE_FORM=TRIM(DOSE_FORM);

--adding all to realtionship_to_concept--

truncate table RELATIONSHIP_TO_CONCEPT
;
insert into RELATIONSHIP_TO_CONCEPT
(CONCEPT_CODE_1,VOCABULARY_ID_1,CONCEPT_ID_2,PRECEDENCE)
select b.concept_code, 'AMT',a .concept_id,a.precedence from aus_dose_forms_done a join drug_concept_stage b on a.dose_form=b.concept_name 
union 
select CONCEPT_CODE,'AMT',CONCEPT_ID,PRECEDENCE from RELATION_INGR_1 a join drug_concept_stage b on a.concept_name= b. concept_name where b.concept_class_id = 'Ingredient' 
;
insert into RELATIONSHIP_TO_CONCEPT
(CONCEPT_CODE_1,VOCABULARY_ID_1,CONCEPT_ID_2)
select CONCEPT_CODE,'AMT',CONCEPT_ID from relation_brandname_1 a join drug_concept_stage b on a.concept_name= b. concept_name where b.concept_class_id = 'Brand Name' 
union 
select CONCEPT_CODE, 'AMT',CONCEPT_ID from manual_supp a join drug_concept_stage b on a.concept_name= b. concept_name where b.concept_class_id = 'Supplier' 
;
insert into RELATIONSHIP_TO_CONCEPT
(CONCEPT_CODE_1,VOCABULARY_ID_1,CONCEPT_ID_2,PRECEDENCE,CONVERSION_FACTOR)
select CONCEPT_CODE,'AMT',CONCEPT_ID_2,PRECEDENCE,CONVERSTION_FACTOR from relation_to_concept_unit
;
update RELATIONSHIP_TO_CONCEPT
set PRECEDENCE = '1' where PRECEDENCE is null
;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43126201 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43126196 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21019309 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21019140 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21020637 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 19131388 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21020344 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21020318 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21019596 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21019581 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43132698 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43132581 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21020344 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21020318 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21019596 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43132698 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 21020360 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43132496 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 19052251 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43132849 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43132829 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43132600 AND   PRECEDENCE = 1;
DELETE FROM RELATIONSHIP_TO_CONCEPT WHERE CONCEPT_ID_2 = 43132357 AND   PRECEDENCE = 1;
UPDATE RELATIONSHIP_TO_CONCEPT  SET PRECEDENCE = 2 WHERE CONCEPT_ID_2 = 43012668 AND   PRECEDENCE = 3;

truncate table pc_stage;
insert into pc_stage (PACK_CONCEPT_CODE,DRUG_CONCEPT_CODE,AMOUNT)
select FO_PRD_ID,CONCEPT_CODE,AMOUNT_PACK from pack_drug_product
join drug_concept_stage on PRD_NAME=concept_name;


