-- input tables creation
DROP TABLE IF EXISTS DRUG_CONCEPT_STAGE;
CREATE TABLE DRUG_CONCEPT_STAGE
(
   CONCEPT_NAME        VARCHAR(255),
   VOCABULARY_ID       VARCHAR(20),
   CONCEPT_CLASS_ID    VARCHAR(25),
   STANDARD_CONCEPT    VARCHAR(1),
   CONCEPT_CODE        VARCHAR(50),
   POSSIBLE_EXCIPIENT  VARCHAR(1),
   DOMAIN_ID           VARCHAR(25),
   VALID_START_DATE    DATE,
   VALID_END_DATE      DATE,
   INVALID_REASON      VARCHAR(1)
);

DROP TABLE IF EXISTS DS_STAGE;
CREATE TABLE DS_STAGE
(
   DRUG_CONCEPT_CODE        VARCHAR(255),
   INGREDIENT_CONCEPT_CODE  VARCHAR(255),
   BOX_SIZE                 INT4,
   AMOUNT_VALUE             FLOAT,
   AMOUNT_UNIT              VARCHAR(255),
   NUMERATOR_VALUE          FLOAT,
   NUMERATOR_UNIT           VARCHAR(255),
   DENOMINATOR_VALUE        FLOAT,
   DENOMINATOR_UNIT         VARCHAR(255)
);

DROP TABLE IF EXISTS INTERNAL_RELATIONSHIP_STAGE;
CREATE TABLE INTERNAL_RELATIONSHIP_STAGE
(
   CONCEPT_CODE_1     VARCHAR(50),
   CONCEPT_CODE_2     VARCHAR(50)
);

DROP TABLE IF EXISTS RELATIONSHIP_TO_CONCEPT;
CREATE TABLE RELATIONSHIP_TO_CONCEPT
(
   CONCEPT_CODE_1     VARCHAR(255),
   VOCABULARY_ID_1    VARCHAR(20),
   CONCEPT_ID_2       INTEGER,
   PRECEDENCE         INTEGER,
   CONVERSION_FACTOR  FLOAT
);

DROP TABLE IF EXISTS PC_STAGE;
CREATE TABLE PC_STAGE
(
   PACK_CONCEPT_CODE  VARCHAR(255),
   DRUG_CONCEPT_CODE  VARCHAR(255),
   AMOUNT             FLOAT,
   BOX_SIZE           INT4
);

DROP TABLE IF EXISTS AU_LPD;
CREATE TABLE AU_LPD
(
    FO_PRD_ID                VARCHAR (255),
    PRD_EID                  VARCHAR (255),
    PRD_NAME                 VARCHAR (255),
    MAST_PRD_NAME            VARCHAR (255),
    INT_BRAND_NAME           VARCHAR (255),
    DOSAGE                   VARCHAR (255),
    DOSAGE_AS_TEXT           VARCHAR (255),
    UNIT                     VARCHAR (255),
    DOSAGE2                  VARCHAR (255),
    DOSAGE2_AS_TEXT          VARCHAR (255),
    UNIT2                    VARCHAR (255),
    DOSAGE3                  VARCHAR (255),
    DOSAGE3_AS_TEXT          VARCHAR (255),
    UNIT3                    VARCHAR (255),
    NBDOSE                   VARCHAR (255),
    NBDOSE_AS_TEXT           VARCHAR (255),
    GALENIC                  VARCHAR (255),
    NBDOSE2                  VARCHAR (255),
    NBDOSE2_AS_TEXT          VARCHAR (255),
    GALENIC2                 VARCHAR (255),
    IS_PRD_REFUNDABLE        VARCHAR (255),
    PRD_REFUNDABLE_RATE      VARCHAR (255),
    PRD_PRICE                VARCHAR (255),
    CANCELED_DAT             VARCHAR (255),
    CREATION_DAT             VARCHAR (255),
    MANUFACTURER_NAME        VARCHAR (255),
    IS_GENERIC               VARCHAR (255),
    IS_HOSP                  VARCHAR (255),
    PRD_START_DAT            VARCHAR (255),
    PRD_END_DAT              VARCHAR (255),
    REGROUPING_CODE          VARCHAR (255),
    EPH_CODE                 VARCHAR (255),
    EPH_NAME                 VARCHAR (255),
    EPH_TYPE                 VARCHAR (255),
    EPH_STATE                VARCHAR (255),
    MOL_EID                  VARCHAR (255),
    MOL_NAME                 VARCHAR (255),
    ATCCODE                  VARCHAR (255),
    ATC_NAME                 VARCHAR (255),
    ATC_MOL                  VARCHAR (255),
    ATC_TYPE                 VARCHAR (255),
    ATC_STATE                VARCHAR (255),
    BNF_EID                  VARCHAR (255),
    BNF_NAME                 VARCHAR (255),
    VERSION                  VARCHAR (255),
    UPDATED                  VARCHAR (255),
    MIN_DOSAGE_BY_DAY_REF    VARCHAR (255),
    MAX_DOSAGE_BY_DAY_REF    VARCHAR (255),
    GAL_ID                   VARCHAR (255),
    GAL_ID2                  VARCHAR (255),
    FIRST_PRD_DATE           VARCHAR (255),
    FIRST_PRE_TRA_ID         VARCHAR (255),
    FIRST_TRA_DATE           VARCHAR (255),
    DDL_ID                   VARCHAR (255),
    DDL_LBL                  VARCHAR (255),
    PRD_VAT                  VARCHAR (255),
    REGROUPING_CODE_2        VARCHAR (255),
    GMP_ID                   VARCHAR (255),
    PRD_ID_DC                VARCHAR (255)
);

DROP TABLE IF EXISTS RELATIONSHIP_MANUAL_INGREDIENT_DONE;
CREATE TABLE RELATIONSHIP_MANUAL_INGREDIENT_DONE
(
    CONCEPT_NAME    VARCHAR (255),
    DUMMY           VARCHAR (255),
    CONCEPT_ID      INT4,
    RXNE_NAME       VARCHAR (255),
    PRECEDENCE      INT4
);

DROP TABLE IF EXISTS I_MAP_POSTPROCESS;
CREATE TABLE I_MAP_POSTPROCESS
(
    FO_PRD_ID            VARCHAR (255),
    PRD_NAME             VARCHAR (255),
    INGREDIENT           VARCHAR (255),
    CONCEPT_ID           INT4,
    CONCEPT_NAME         VARCHAR (255),
    VOCABULARY_ID        VARCHAR (255),
    BOX_SIZE             INT4,
    AMOUNT_VALUE         FLOAT,
    AMOUNT_UNIT          VARCHAR (255),
    NUMERATOR_VALUE      FLOAT,
    NUMERATOR_UNIT       VARCHAR (255),
    DENOMINATOR_VALUE    FLOAT,
    DENOMINATOR_UNIT     VARCHAR (255),
    DOSE_FORM            VARCHAR (255)
);

DROP TABLE IF EXISTS NO_DS_DONE;
CREATE TABLE NO_DS_DONE
(
    FO_PRD_ID            VARCHAR (255),
    PRD_NAME             VARCHAR (255),
    MAST_PRD_NAME        VARCHAR (255),
    DOSAGE               VARCHAR (255),
    UNIT                 VARCHAR (255),
    DOSAGE2              VARCHAR (255),
    UNIT2                VARCHAR (255),
    MOL_EID              VARCHAR (255),
    MOL_NAME             VARCHAR (255),
    ATC_NAME             VARCHAR (255),
    MANUFACTURER         VARCHAR (255),
    INGREDIENT_NAME      VARCHAR (255),
    BOX_SIZE             VARCHAR (255),
    AMOUNT_VALUE         FLOAT,
    AMOUNT_UNIT          VARCHAR (255),
    NUMERATOR_VALUE      FLOAT,
    NUMERATOR_UNIT       VARCHAR (255),
    DENOMINATOR_VALUE    FLOAT,
    DENOMINATOR_UNIT     VARCHAR (255)
);

DROP TABLE IF EXISTS PACK_DRUG_PRODUCT_2;
CREATE TABLE PACK_DRUG_PRODUCT_2
(
    FO_PRD_ID            VARCHAR (255),
    PACK_NAME            VARCHAR (255),
    PRD_NAME             VARCHAR (255),
    MOL_NAME             VARCHAR (255),
    AMOUNT_VALUE         FLOAT,
    AMOUNT_UNIT          VARCHAR (255),
    NUMERATOR_VALUE      FLOAT,
    NIMERATOT_UNIT       VARCHAR (255),
    DENOMINATOR_VALUE    FLOAT,
    DENOMINATOR_UNIT     VARCHAR (255),
    AMOUNT_PACK          INT
);

DROP TABLE IF EXISTS RELATIONSHIP_MANUAL_BRAND_DONE;
CREATE TABLE RELATIONSHIP_MANUAL_BRAND_DONE
(
    CONCEPT_NAME    VARCHAR (255),
    DUMMY           VARCHAR (255),
    CONCEPT_ID      INT4,
    RXNE_NAME       VARCHAR (255),
    PRECEDENCE      INT4
);

DROP TABLE IF EXISTS RELATIONSHIP_MANUAL_SUPPLIER_DONE;
CREATE TABLE RELATIONSHIP_MANUAL_SUPPLIER_DONE
(
    CONCEPT_NAME    VARCHAR (255),
    DUMMY           VARCHAR (255),
    CONCEPT_ID      INT4,
    RXNE_NAME       VARCHAR (255),
    PRECEDENCE      INT4
);

DROP TABLE IF EXISTS DS_STAGE_MANUAL_ALL;
CREATE TABLE DS_STAGE_MANUAL_ALL
(
    DRUG_CONCEPT_CODE    VARCHAR (255),
    INGREDIENT_NAME      VARCHAR (255),
    BOX_SIZE             INT4,
    AMOUNT_VALUE         FLOAT,
    AMOUNT_UNIT          VARCHAR (255),
    NUMERATOR_VALUE      FLOAT,
    NUMERATOR_UNIT       VARCHAR (255),
    DENOMINATOR_VALUE    FLOAT,
    DENOMINATOR_UNIT     VARCHAR (255)
);

DROP TABLE IF EXISTS DS_TO_DELETE_DONE;
CREATE TABLE DS_TO_DELETE_DONE
(
    FO_PRD_ID                  VARCHAR (255),
    PRD_NAME                   VARCHAR (255),
    MOL_NAME                   VARCHAR (255),
    INGREDIENT_CONCEPT_CODE    VARCHAR (255),
    CONCEPT_NAME               VARCHAR (255),
    BOX_SIZE                   INT,
    AMOUNT_VALUE               FLOAT,
    AMOUNT_UNIT                VARCHAR (20),
    NUMERATOR_VALUE            FLOAT,
    NUMERATOR_UNIT             VARCHAR (20),
    DENOMINATOR_VALUE          FLOAT,
    DENOMINATOR_UNIT           VARCHAR (20),
    VALID_DS                   INT
);

DROP TABLE IF EXISTS RELATION_MANUAL_BN;
CREATE TABLE RELATION_MANUAL_BN
(
    CONCEPT_CODE          VARCHAR (255),
    CONCEPT_NAME          VARCHAR (255),
    CONCEPT_ID_2          INT4,
    CONCEPT_NAME_2        VARCHAR (255),
    PRECEDENCE            INT,
    CONVERSTION_FACTOR    FLOAT
);

DROP TABLE IF EXISTS AUS_DOSE_FORMS_DONE;
CREATE TABLE AUS_DOSE_FORMS_DONE
(
    DOSE_FORM       VARCHAR (255),
    CONCEPT_ID      INT4,
    CONCEPT_NAME    VARCHAR (255),
    PRECEDENCE      INT
);

DROP TABLE IF EXISTS MANUAL_SUPP;
CREATE TABLE MANUAL_SUPP
(
    CONCEPT_NAME     VARCHAR (255),
    CONCEPT_ID       INT NOT NULL,
    RCONCEPT_NAME    VARCHAR (255) NOT NULL
);

DROP TABLE IF EXISTS AUS_UNIT_DONE;
CREATE TABLE AUS_UNIT_DONE
(
    CONCEPT_CODE_1       VARCHAR (255),
    VOCABULARY_ID_1      VARCHAR (20),
    CONCEPT_ID_2         INT4,
    PRECEDENCE           INT,
    CONVERSION_FACTOR    FLOAT
);