CREATE TABLE FO_PRODUCT
(
   FO_PRD_ID              VARCHAR2(255 Byte),
   PRD_EID                VARCHAR2(255 Byte),
   PRD_NAME               VARCHAR2(255 Byte),
   MAST_PRD_NAME          VARCHAR2(255 Byte),
   INT_BRAND_NAME         VARCHAR2(255 Byte),
   DOSAGE                 VARCHAR2(255 Byte),
   DOSAGE_AS_TEXT         VARCHAR2(255 Byte),
   UNIT                   VARCHAR2(255 Byte),
   DOSAGE2                VARCHAR2(255 Byte),
   DOSAGE2_AS_TEXT        VARCHAR2(255 Byte),
   UNIT2                  VARCHAR2(255 Byte),
   DOSAGE3                VARCHAR2(255 Byte),
   DOSAGE3_AS_TEXT        VARCHAR2(255 Byte),
   UNIT3                  VARCHAR2(255 Byte),
   NBDOSE                 VARCHAR2(255 Byte),
   NBDOSE_AS_TEXT         VARCHAR2(255 Byte),
   GALENIC                VARCHAR2(255 Byte),
   NBDOSE2                VARCHAR2(255 Byte),
   NBDOSE2_AS_TEXT        VARCHAR2(255 Byte),
   GALENIC2               VARCHAR2(255 Byte),
   IS_PRD_REFUNDABLE      VARCHAR2(255 Byte),
   PRD_REFUNDABLE_RATE    VARCHAR2(255 Byte),
   PRD_PRICE              VARCHAR2(255 Byte),
   CANCELED_DAT           VARCHAR2(255 Byte),
   CREATION_DAT           VARCHAR2(255 Byte),
   MANUFACTURER_NAME      VARCHAR2(255 Byte),
   IS_GENERIC             VARCHAR2(255 Byte),
   IS_HOSP                VARCHAR2(255 Byte),
   PRD_START_DAT          VARCHAR2(255 Byte),
   PRD_END_DAT            VARCHAR2(255 Byte),
   REGROUPING_CODE        VARCHAR2(255 Byte),
   EPH_CODE               VARCHAR2(255 Byte),
   EPH_NAME               VARCHAR2(255 Byte),
   EPH_TYPE               VARCHAR2(255 Byte),
   EPH_STATE              VARCHAR2(255 Byte),
   MOL_EID                VARCHAR2(255 Byte),
   MOL_NAME               VARCHAR2(255 Byte),
   ATCCODE                VARCHAR2(255 Byte),
   ATC_NAME               VARCHAR2(255 Byte),
   ATC_MOL                VARCHAR2(255 Byte),
   ATC_TYPE               VARCHAR2(255 Byte),
   ATC_STATE              VARCHAR2(255 Byte),
   BNF_EID                VARCHAR2(255 Byte),
   BNF_NAME               VARCHAR2(255 Byte),
   VERSION                VARCHAR2(255 Byte),
   UPDATED                VARCHAR2(255 Byte),
   MIN_DOSAGE_BY_DAY_REF  VARCHAR2(255 Byte),
   MAX_DOSAGE_BY_DAY_REF  VARCHAR2(255 Byte),
   GAL_ID                 VARCHAR2(255 Byte),
   GAL_ID2                VARCHAR2(255 Byte),
   FIRST_PRD_DATE         VARCHAR2(255 Byte),
   FIRST_PRE_TRA_ID       VARCHAR2(255 Byte),
   FIRST_TRA_DATE         VARCHAR2(255 Byte),
   DDL_ID                 VARCHAR2(255 Byte),
   DDL_LBL                VARCHAR2(255 Byte),
   PRD_VAT                VARCHAR2(255 Byte),
   REGROUPING_CODE_2      VARCHAR2(255 Byte),
   GMP_ID                 VARCHAR2(255 Byte),
   PRD_ID_DC              VARCHAR2(255 Byte)
)
TABLESPACE USERS;


CREATE TABLE DRUG_MAPPING
(
   PRD_EID          VARCHAR2(255 Byte),
   LPDORIGINALNAME  VARCHAR2(255 Byte),
   FCC              VARCHAR2(255 Byte),
   DESCRIPTION      VARCHAR2(255 Byte),
   MANUFACTURER     VARCHAR2(255 Byte),
   EPHMRA_ATC_CODE  VARCHAR2(255 Byte),
   NFC_CODE         VARCHAR2(255 Byte),
   PRD_NAME         VARCHAR2(255 Byte),
   MAST_PRD_NAME    VARCHAR2(255 Byte),
   WHO_ATC_EID      VARCHAR2(255 Byte),
   PRD_DOSAGE       VARCHAR2(255 Byte),
   UNIT             VARCHAR2(255 Byte),
   PRD_DOSAGE2      VARCHAR2(255 Byte),
   UNIT_ID2         VARCHAR2(255 Byte),
   MOL_NAME         VARCHAR2(255 Byte)
)
TABLESPACE USERS;



CREATE TABLE FO_PRODUCT_p2
(
   FO_PRD_ID              VARCHAR2(255 Byte),
   PRD_EID                VARCHAR2(255 Byte),
   PRD_NAME               VARCHAR2(255 Byte),
   MAST_PRD_NAME          VARCHAR2(255 Byte),
   INT_BRAND_NAME         VARCHAR2(255 Byte),
   DOSAGE                 VARCHAR2(255 Byte),
   DOSAGE_AS_TEXT         VARCHAR2(255 Byte),
   UNIT                   VARCHAR2(255 Byte),
   DOSAGE2                VARCHAR2(255 Byte),
   DOSAGE2_AS_TEXT        VARCHAR2(255 Byte),
   UNIT2                  VARCHAR2(255 Byte),
   DOSAGE3                VARCHAR2(255 Byte),
   DOSAGE3_AS_TEXT        VARCHAR2(255 Byte),
   UNIT3                  VARCHAR2(255 Byte),
   NBDOSE                 VARCHAR2(255 Byte),
   NBDOSE_AS_TEXT         VARCHAR2(255 Byte),
   GALENIC                VARCHAR2(255 Byte),
   NBDOSE2                VARCHAR2(255 Byte),
   NBDOSE2_AS_TEXT        VARCHAR2(255 Byte),
   GALENIC2               VARCHAR2(255 Byte),
   IS_PRD_REFUNDABLE      VARCHAR2(255 Byte),
   PRD_REFUNDABLE_RATE    VARCHAR2(255 Byte),
   PRD_PRICE              VARCHAR2(255 Byte),
   CANCELED_DAT           VARCHAR2(255 Byte),
   CREATION_DAT           VARCHAR2(255 Byte),
   MANUFACTURER_NAME      VARCHAR2(255 Byte),
   IS_GENERIC             VARCHAR2(255 Byte),
   IS_HOSP                VARCHAR2(255 Byte),
   PRD_START_DAT          VARCHAR2(255 Byte),
   PRD_END_DAT            VARCHAR2(255 Byte),
   REGROUPING_CODE        VARCHAR2(255 Byte),
   EPH_CODE               VARCHAR2(255 Byte),
   EPH_NAME               VARCHAR2(255 Byte),
   EPH_TYPE               VARCHAR2(255 Byte),
   EPH_STATE              VARCHAR2(255 Byte),
   MOL_EID                VARCHAR2(255 Byte),
   MOL_NAME               VARCHAR2(255 Byte),
   ATCCODE                VARCHAR2(255 Byte),
   ATC_NAME               VARCHAR2(255 Byte),
   ATC_MOL                VARCHAR2(255 Byte),
   ATC_TYPE               VARCHAR2(255 Byte),
   ATC_STATE              VARCHAR2(255 Byte),
   BNF_EID                VARCHAR2(255 Byte),
   BNF_NAME               VARCHAR2(255 Byte),
   VERSION                VARCHAR2(255 Byte),
   UPDATED                VARCHAR2(255 Byte),
   MIN_DOSAGE_BY_DAY_REF  VARCHAR2(255 Byte),
   MAX_DOSAGE_BY_DAY_REF  VARCHAR2(255 Byte),
   GAL_ID                 VARCHAR2(255 Byte),
   GAL_ID2                VARCHAR2(255 Byte),
   FIRST_PRD_DATE         VARCHAR2(255 Byte),
   FIRST_PRE_TRA_ID       VARCHAR2(255 Byte),
   FIRST_TRA_DATE         VARCHAR2(255 Byte),
   DDL_ID                 VARCHAR2(255 Byte),
   DDL_LBL                VARCHAR2(255 Byte),
   PRD_VAT                VARCHAR2(255 Byte),
   REGROUPING_CODE_2      VARCHAR2(255 Byte),
   GMP_ID                 VARCHAR2(255 Byte),
   PRD_ID_DC              VARCHAR2(255 Byte)
)
;
CREATE TABLE DRUG_MAPPING_p2
(
   PRD_EID          VARCHAR2(255 Byte),
   LPDORIGINALNAME  VARCHAR2(255 Byte),
   FCC              VARCHAR2(255 Byte),
   DESCRIPTION      VARCHAR2(255 Byte),
   MANUFACTURER     VARCHAR2(255 Byte),
   EPHMRA_ATC_CODE  VARCHAR2(255 Byte),
   NFC_CODE         VARCHAR2(255 Byte),
   PRD_NAME         VARCHAR2(255 Byte),
   MAST_PRD_NAME    VARCHAR2(255 Byte),
   WHO_ATC_EID      VARCHAR2(255 Byte),
   PRD_DOSAGE       VARCHAR2(255 Byte),
   UNIT             VARCHAR2(255 Byte),
   PRD_DOSAGE2      VARCHAR2(255 Byte),
   UNIT_ID2         VARCHAR2(255 Byte),
   MOL_NAME         VARCHAR2(255 Byte)
);


CREATE TABLE DRUG_MAPPING_3
(
   PRD_EID          VARCHAR2(255 Byte),
   LPDORIGINALNAME  VARCHAR2(255 Byte),
   FCC              VARCHAR2(255 Byte),
   DESCRIPTION      VARCHAR2(255 Byte),
   MANUFACTURER     VARCHAR2(255 Byte),
   EPHMRA_ATC_CODE  VARCHAR2(255 Byte),
   NFC_CODE         VARCHAR2(255 Byte),
   PRD_NAME         VARCHAR2(255 Byte),
   MAST_PRD_NAME    VARCHAR2(255 Byte),
   WHO_ATC_EID      VARCHAR2(255 Byte),
   PRD_DOSAGE       VARCHAR2(255 Byte),
   UNIT             VARCHAR2(255 Byte),
   PRD_DOSAGE2      VARCHAR2(255 Byte),
   UNIT_ID2         VARCHAR2(255 Byte),
   MOL_NAME         VARCHAR2(255 Byte)
)
TABLESPACE USERS;

CREATE TABLE FO_PRODUCT_3
(
   FO_PRD_ID              VARCHAR2(255 Byte),
   PRD_EID                VARCHAR2(255 Byte),
   PRD_NAME               VARCHAR2(255 Byte),
   MAST_PRD_NAME          VARCHAR2(255 Byte),
   INT_BRAND_NAME         VARCHAR2(255 Byte),
   DOSAGE                 VARCHAR2(255 Byte),
   DOSAGE_AS_TEXT         VARCHAR2(255 Byte),
   UNIT                   VARCHAR2(255 Byte),
   DOSAGE2                VARCHAR2(255 Byte),
   DOSAGE2_AS_TEXT        VARCHAR2(255 Byte),
   UNIT2                  VARCHAR2(255 Byte),
   DOSAGE3                VARCHAR2(255 Byte),
   DOSAGE3_AS_TEXT        VARCHAR2(255 Byte),
   UNIT3                  VARCHAR2(255 Byte),
   NBDOSE                 VARCHAR2(255 Byte),
   NBDOSE_AS_TEXT         VARCHAR2(255 Byte),
   GALENIC                VARCHAR2(255 Byte),
   NBDOSE2                VARCHAR2(255 Byte),
   NBDOSE2_AS_TEXT        VARCHAR2(255 Byte),
   GALENIC2               VARCHAR2(255 Byte),
   IS_PRD_REFUNDABLE      VARCHAR2(255 Byte),
   PRD_REFUNDABLE_RATE    VARCHAR2(255 Byte),
   PRD_PRICE              VARCHAR2(255 Byte),
   CANCELED_DAT           VARCHAR2(255 Byte),
   CREATION_DAT           VARCHAR2(255 Byte),
   MANUFACTURER_NAME      VARCHAR2(255 Byte),
   IS_GENERIC             VARCHAR2(255 Byte),
   IS_HOSP                VARCHAR2(255 Byte),
   PRD_START_DAT          VARCHAR2(255 Byte),
   PRD_END_DAT            VARCHAR2(255 Byte),
   REGROUPING_CODE        VARCHAR2(255 Byte),
   EPH_CODE               VARCHAR2(255 Byte),
   EPH_NAME               VARCHAR2(255 Byte),
   EPH_TYPE               VARCHAR2(255 Byte),
   EPH_STATE              VARCHAR2(255 Byte),
   MOL_EID                VARCHAR2(255 Byte),
   MOL_NAME               VARCHAR2(255 Byte),
   ATCCODE                VARCHAR2(255 Byte),
   ATC_NAME               VARCHAR2(255 Byte),
   ATC_MOL                VARCHAR2(255 Byte),
   ATC_TYPE               VARCHAR2(255 Byte),
   ATC_STATE              VARCHAR2(255 Byte),
   BNF_EID                VARCHAR2(255 Byte),
   BNF_NAME               VARCHAR2(255 Byte),
   VERSION                VARCHAR2(255 Byte),
   UPDATED                VARCHAR2(255 Byte),
   MIN_DOSAGE_BY_DAY_REF  VARCHAR2(255 Byte),
   MAX_DOSAGE_BY_DAY_REF  VARCHAR2(255 Byte),
   GAL_ID                 VARCHAR2(255 Byte),
   GAL_ID2                VARCHAR2(255 Byte),
   FIRST_PRD_DATE         VARCHAR2(255 Byte),
   FIRST_PRE_TRA_ID       VARCHAR2(255 Byte),
   FIRST_TRA_DATE         VARCHAR2(255 Byte),
   DDL_ID                 VARCHAR2(255 Byte),
   DDL_LBL                VARCHAR2(255 Byte),
   PRD_VAT                VARCHAR2(255 Byte),
   REGROUPING_CODE_2      VARCHAR2(255 Byte),
   GMP_ID                 VARCHAR2(255 Byte),
   PRD_ID_DC              VARCHAR2(255 Byte)
)
TABLESPACE USERS;
