CREATE TABLE KEYV2
(
  TERMCLASS          VARCHAR2(10 BYTE),
  CLASSNUMBER        VARCHAR2(2 BYTE),
  DESCRIPTION_SHORT  VARCHAR2(30 BYTE),
  DESCRIPTION        VARCHAR2(60 BYTE),
  DESCRIPTION_LONG   VARCHAR2(200 BYTE),
  TERMCODE           VARCHAR2(2 BYTE),
  LANG               VARCHAR2(2 BYTE),
  READCODE           VARCHAR2(5 BYTE),
  DIGIT              VARCHAR2(1 BYTE)
);

CREATE TABLE RCSCTMAP2_UK
(
  MAPID          VARCHAR2(38 BYTE),
  READCODE       VARCHAR2(5 BYTE),
  TERMCODE       VARCHAR2(2 BYTE),
  CONCEPTID      VARCHAR2(18 BYTE),
  DESCRIPTIONID  VARCHAR2(18 BYTE),
  IS_ASSURED     VARCHAR2(1 BYTE),
  EFFECTIVEDATE  DATE,
  MAPSTATUS      VARCHAR2(2 BYTE)
);