/**************************************************************************
* Copyright 2016 Observational Health Data Sciences and Informatics (OHDSI)
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
* 
* Authors: Timur Vakhitov, Christian Reich
* Date: 2016
**************************************************************************/

DROP TABLE PRODV5.CONCEPT PURGE;
DROP TABLE PRODV5.VOCABULARY PURGE;
DROP TABLE PRODV5.CONCEPT_RELATIONSHIP PURGE;
DROP TABLE PRODV5.RELATIONSHIP PURGE;
DROP TABLE PRODV5.CONCEPT_SYNONYM PURGE;
DROP TABLE PRODV5.CONCEPT_ANCESTOR PURGE;
DROP TABLE PRODV5.DOMAIN PURGE;
DROP TABLE PRODV5.DRUG_STRENGTH PURGE;
DROP TABLE PRODV5.CONCEPT_CLASS PURGE;
DROP TABLE PRODV5.VOCABULARY_CONVERSION PURGE;
DROP TABLE PRODV5.EXISTING_DS PURGE;

-- Copy all relevant tables from DevV5

CREATE TABLE PRODV5.CONCEPT AS SELECT * FROM DEVV5.CONCEPT;
CREATE TABLE PRODV5.VOCABULARY AS SELECT * FROM DEVV5.VOCABULARY;
CREATE TABLE PRODV5.CONCEPT_RELATIONSHIP AS SELECT * FROM DEVV5.CONCEPT_RELATIONSHIP;
CREATE TABLE PRODV5.RELATIONSHIP AS SELECT * FROM DEVV5.RELATIONSHIP;
CREATE TABLE PRODV5.CONCEPT_SYNONYM AS SELECT * FROM DEVV5.CONCEPT_SYNONYM;
CREATE TABLE PRODV5.CONCEPT_ANCESTOR AS SELECT * FROM DEVV5.CONCEPT_ANCESTOR;
CREATE TABLE PRODV5.DOMAIN AS SELECT * FROM DEVV5.DOMAIN;
CREATE TABLE PRODV5.DRUG_STRENGTH AS SELECT * FROM DEVV5.DRUG_STRENGTH;
CREATE TABLE PRODV5.CONCEPT_CLASS AS SELECT * FROM DEVV5.CONCEPT_CLASS;
CREATE TABLE PRODV5.VOCABULARY_CONVERSION AS SELECT * FROM DEVV5.VOCABULARY_CONVERSION;
CREATE TABLE PRODV5.EXISTING_DS AS SELECT * FROM DEVV5.EXISTING_DS;

UPDATE PRODV5.VOCABULARY SET VOCABULARY_NAME = 'OMOP Standardized Vocabularies', VOCABULARY_VERSION = 'v5.0 '||SYSDATE WHERE VOCABULARY_ID = 'None';

ALTER TABLE PRODV5.CONCEPT ADD CONSTRAINT XPK_CONCEPT PRIMARY KEY (CONCEPT_ID);
CREATE INDEX PRODV5.CONCEPT_VOCAB ON PRODV5.CONCEPT (VOCABULARY_ID);

CREATE INDEX PRODV5.CONCEPT_RELATIONSHIP_C_1 ON PRODV5.CONCEPT_RELATIONSHIP (CONCEPT_ID_1);
CREATE INDEX PRODV5.CONCEPT_RELATIONSHIP_C_2 ON PRODV5.CONCEPT_RELATIONSHIP (CONCEPT_ID_2);

CREATE INDEX PRODV5.CONCEPT_SYNONYM_CONCEPT ON PRODV5.CONCEPT_SYNONYM (CONCEPT_ID);

CREATE INDEX PRODV5.ANCESTOR_CONCEPTID ON PRODV5.CONCEPT_ANCESTOR (ANCESTOR_CONCEPT_ID);
CREATE INDEX PRODV5.DESCENDANT_CONCEPTID ON PRODV5.CONCEPT_ANCESTOR (DESCENDANT_CONCEPT_ID);

CREATE INDEX PRODV5.DRUG_CONCEPTID ON PRODV5.DRUG_STRENGTH (DRUG_CONCEPT_ID);
CREATE INDEX PRODV5.INGREDIENT_CONCEPTID ON PRODV5.DRUG_STRENGTH (INGREDIENT_CONCEPT_ID);

GRANT SELECT ON VOCAB_DOWNLOAD.VOCABULARY_USER TO PRODV5;
GRANT SELECT ON CONCEPT TO DEVV5;
GRANT SELECT ON CONCEPT_RELATIONSHIP TO DEVV5;
GRANT SELECT ON CONCEPT_ANCESTOR TO DEVV5;