/**************************************************************************
* Copyright 2016 Observational Health Data Sciences and Informatics (OHDSI)
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
* 
* Authors: Timur Vakhitov, Christian Reich
* Date: 2016
**************************************************************************/

DROP TABLE PRODV4.CONCEPT PURGE;
DROP TABLE PRODV4.VOCABULARY PURGE;
DROP TABLE PRODV4.CONCEPT_RELATIONSHIP PURGE;
DROP TABLE PRODV4.RELATIONSHIP PURGE;
DROP TABLE PRODV4.CONCEPT_SYNONYM PURGE;
DROP TABLE PRODV4.CONCEPT_ANCESTOR PURGE;
DROP TABLE PRODV4.SOURCE_TO_CONCEPT_MAP PURGE;
DROP TABLE PRODV4.DRUG_STRENGTH PURGE;

-- Copy all relevant tables from DevV4

CREATE TABLE PRODV4.CONCEPT AS SELECT * FROM DEVV4.CONCEPT;
CREATE TABLE PRODV4.VOCABULARY AS SELECT * FROM DEVV4.VOCABULARY;
CREATE TABLE PRODV4.CONCEPT_RELATIONSHIP AS SELECT * FROM DEVV4.CONCEPT_RELATIONSHIP;
CREATE TABLE PRODV4.RELATIONSHIP AS SELECT * FROM DEVV4.RELATIONSHIP;
CREATE TABLE PRODV4.CONCEPT_SYNONYM AS SELECT * FROM DEVV4.CONCEPT_SYNONYM;
CREATE TABLE PRODV4.CONCEPT_ANCESTOR AS SELECT * FROM DEVV4.CONCEPT_ANCESTOR;
CREATE TABLE PRODV4.SOURCE_TO_CONCEPT_MAP AS SELECT * FROM DEVV4.SOURCE_TO_CONCEPT_MAP;
CREATE TABLE PRODV4.DRUG_STRENGTH AS SELECT * FROM DEVV4.DRUG_STRENGTH;

UPDATE PRODV4.VOCABULARY SET VOCABULARY_NAME='OMOP Vocabulary v4.5 '||SYSDATE WHERE VOCABULARY_ID=0;

ALTER TABLE PRODV4.CONCEPT ADD CONSTRAINT XPK_CONCEPT PRIMARY KEY (CONCEPT_ID);
CREATE INDEX PRODV4.CONCEPT_VOCAB ON PRODV4.CONCEPT (VOCABULARY_ID);

CREATE INDEX PRODV4.CONCEPT_RELATIONSHIP_C_1 ON PRODV4.CONCEPT_RELATIONSHIP (CONCEPT_ID_1);
CREATE INDEX PRODV4.CONCEPT_RELATIONSHIP_C_2 ON PRODV4.CONCEPT_RELATIONSHIP (CONCEPT_ID_2);

CREATE INDEX PRODV4.CONCEPT_SYNONYM_CONCEPT ON PRODV4.CONCEPT_SYNONYM (CONCEPT_ID);