CREATE TABLE PRODUCT
(
  PRODUCTID                  VARCHAR2(50 BYTE),
  PRODUCTNDC                 VARCHAR2(10 BYTE),
  PRODUCTTYPENAME            VARCHAR2(27 BYTE),
  PROPRIETARYNAME            VARCHAR2(226 BYTE),
  PROPRIETARYNAMESUFFIX      VARCHAR2(126 BYTE),
  NONPROPRIETARYNAME         VARCHAR2(4000 BYTE),
  DOSAGEFORMNAME             VARCHAR2(48 BYTE),
  ROUTENAME                  VARCHAR2(118 BYTE),
  STARTMARKETINGDATE         DATE,
  ENDMARKETINGDATE           DATE,
  MARKETINGCATEGORYNAME      VARCHAR2(40 BYTE),
  APPLICATIONNUMBER          VARCHAR2(100 BYTE),
  LABELERNAME                VARCHAR2(100 BYTE),
  SUBSTANCENAME              VARCHAR2(4000 BYTE),
  ACTIVE_NUMERATOR_STRENGTH  VARCHAR2(4000 BYTE),
  ACTIVE_INGRED_UNIT         VARCHAR2(4000 BYTE),
  PHARM_CLASSES              VARCHAR2(4000 BYTE),
  DEASCHEDULE                VARCHAR2(5 BYTE)
);